import type { RuleDef } from "../../types";
import { CWE, OSV, OWASP, def } from "./shared";

/** Rules in the `secrets` category. Order matters: it is the order the report prints. */
export const secretsRules: RuleDef[] = [
  def({
    id: "SEC-001",
    engine: "secrets",
    category: "secrets",
    severity: "HIGH",
    confidence: 0.92,
    languages: "all",
    title: ["مفتاح أو كلمة مرور مكتوبة داخل الكود", "Hardcoded credential in source"],
    description: [
      "تم العثور على قيمة تشبه مفتاح API أو كلمة مرور مكتوبة مباشرة في ملف مصدري.",
      "A value that looks like an API key or password is written directly into a source file.",
    ],
    impact: [
      "أي شخص لديه وصول للكود (أو لتاريخ Git) يمكنه استخدام المفتاح، وتغييره لاحقًا مكلف.",
      "Anyone with repository access — including its Git history — can use the key, and rotating it later is costly.",
    ],
    recommendation: [
      "انقل القيمة إلى متغير بيئة أو مدير أسرار، ثم أبطِل المفتاح المكشوف وأنشئ بديلًا.",
      "Move the value to an environment variable or secret manager, then revoke the exposed key and issue a new one.",
    ],
    detection: ["نمط نصّي + فحص سياق المتغير", "Pattern match plus variable-context check"],
    references: [CWE(798), OWASP],
  }),
  def({
    id: "SEC-002",
    engine: "secrets",
    category: "secrets",
    severity: "CRITICAL",
    confidence: 0.96,
    languages: "all",
    title: ["مفتاح خاص (Private Key) داخل المستودع", "Private key committed to the repository"],
    description: [
      "كتلة مفتاح خاص (RSA/EC/OpenSSH/PGP) موجودة في ملفات المشروع.",
      "A private key block (RSA/EC/OpenSSH/PGP) is present in the project files.",
    ],
    impact: [
      "تسريب مفتاح خاص يسمح بانتحال هوية الخدمة أو فك الاتصالات المشفّرة.",
      "A leaked private key allows impersonating the service or decrypting its traffic.",
    ],
    recommendation: [
      "احذف المفتاح من المستودع ومن تاريخ Git، وأنشئ مفتاحًا جديدًا، واستخدم مخزن أسرار.",
      "Remove the key from the repository and its Git history, generate a new key, and store it in a secret manager.",
    ],
    detection: ["تعرّف على رؤوس المفاتيح الخاصة", "Private-key header detection"],
    references: [CWE(321)],
  }),
  def({
    id: "SEC-003",
    engine: "secrets",
    category: "secrets",
    severity: "HIGH",
    confidence: 0.85,
    languages: "all",
    title: ["توكن وصول مكتوب في الكود", "Access token literal in code"],
    description: [
      "توكن مصادقة (Bearer/JWT/سلسلة طويلة عالية العشوائية) موضوع في ملف مصدري.",
      "An authentication token (Bearer/JWT/high-entropy string) is embedded in a source file.",
    ],
    impact: ["التوكن يمنح وصولًا للنظام باسم المالك حتى انتهاء صلاحيته.", "The token grants access on the owner's behalf until it expires."],
    recommendation: [
      "استخدم متغيرات بيئة وجلسات قصيرة العمر، وأبطِل التوكن الحالي.",
      "Use environment variables and short-lived sessions, and revoke the current token.",
    ],
    detection: ["أنماط توكنات (JWT, Bearer, بادئات مزوّدين) + Entropy", "Token patterns (JWT, Bearer, provider prefixes) plus entropy"],
    references: [CWE(522)],
  }),
  def({
    id: "SEC-004",
    engine: "secrets",
    category: "secrets",
    severity: "HIGH",
    confidence: 0.8,
    languages: "all",
    title: ["ملف أسرار مُلتزَم في المستودع", "A secrets file is committed"],
    description: [
      "ملف بيئة أو مفتاح (‎.env, .env.local, secrets.yml …) مرفوع مع المشروع ويحمل قيمًا حقيقية.",
      "An environment or key file (.env, .env.local, secrets.yml …) ships with the project and holds real values.",
    ],
    impact: ["كل من يقرأ المستودع يحصل على أسرار البيئة كاملة.", "Everyone who can read the repository gets the complete environment secrets."],
    recommendation: [
      "احتفظ بملف مثال فقط (.env.example) وامنع الملف الحقيقي في .gitignore.",
      "Keep only an example file (.env.example) and ignore the real one in .gitignore.",
    ],
    detection: ["أسماء الملفات + وجود قيم غير نموذجية", "File-name check plus presence of non-placeholder values"],
    references: [CWE(538)],
  }),
  def({
    id: "SEC-005",
    engine: "secrets",
    category: "secrets",
    severity: "MEDIUM",
    confidence: 0.6,
    languages: "all",
    title: ["نص عالي العشوائية يُسند إلى متغير سري", "High-entropy literal assigned to a secret-looking variable"],
    description: [
      "متغير اسمه يشير إلى سر (secret/key/password) يحمل نصًا طويلًا عشوائيًا ثابتًا.",
      "A variable named like a secret (secret/key/password) holds a long, fixed, random-looking string.",
    ],
    impact: ["قد يكون مفتاحًا حقيقيًا لم يُلاحظ؛ وقد يكون قيمة اختبار — يحتاج تأكيدًا بشريًا.", "May be a real key that went unnoticed, or a test value — needs human confirmation."],
    recommendation: ["انقله إلى متغير بيئة أو أضف تعليقًا صريحًا إن كان قيمة اختبار.", "Move it to an environment variable, or mark it explicitly if it is a test value."],
    detection: ["Entropy + اسم المتغير", "Entropy plus variable naming"],
    references: [CWE(798)],
  }),
  def({
    id: "SEC-006",
    engine: "secrets",
    category: "secrets",
    severity: "HIGH",
    confidence: 0.9,
    languages: "all",
    title: ["رابط قاعدة بيانات يحمل كلمة مرور", "Database URL carrying credentials"],
    description: [
      "سلسلة اتصال تحتوي على اسم مستخدم وكلمة مرور ظاهرة داخل الكود.",
      "A connection string containing a visible username and password appears in code.",
    ],
    impact: ["وصول مباشر لقاعدة البيانات من أي شخص يرى الملف.", "Direct database access for anyone who sees the file."],
    recommendation: ["اقرأ السلسلة من متغير بيئة، وقيّد صلاحيات المستخدم، وغيّر كلمة المرور.", "Read the string from an environment variable, restrict the account, and rotate the password."],
    detection: ["نمط بروتوكولات قواعد البيانات مع بيانات اعتماد", "Database protocol patterns with inline credentials"],
    references: [CWE(798)],
  }),
  def({
    id: "SEC-007",
    engine: "secrets",
    category: "secrets",
    severity: "HIGH",
    confidence: 0.88,
    languages: "all",
    title: ["بيانات اعتماد داخل رابط", "Credentials embedded in a URL"],
    description: [
      "رابط بصيغة https://user:password@host ينشر كلمة المرور كنص صريح.",
      "A URL of the form https://user:password@host exposes the password in clear text.",
    ],
    impact: ["كلمة المرور تظهر في السجلات وأدوات المراقبة ورسائل الأخطاء.", "The password leaks into logs, monitoring tools and error messages."],
    recommendation: ["أزل بيانات الاعتماد من الرابط واستخدم ترويسة مصادقة أو مدير أسرار.", "Remove credentials from the URL and use an auth header or secret manager."],
    detection: ["نمط URL مع عنصر مصادقة", "URL pattern with a userinfo component"],
    references: [CWE(522)],
  }),
];
