import type { RuleDef } from "../../types";
import { CWE, OSV, OWASP, def } from "./shared";

/** Rules in the `security` category. Order matters: it is the order the report prints. */
export const securityRules: RuleDef[] = [
  def({
    id: "SEC-101",
    engine: "security",
    category: "security",
    severity: "HIGH",
    confidence: 0.85,
    languages: ["javascript", "typescript", "php", "python"],
    title: ["استخدام eval أو كود ديناميكي", "Use of eval or dynamic code execution"],
    description: [
      "تنفيذ نص ككود (eval / new Function / exec) ويمكن أن يصل إليه مدخل مستخدم.",
      "A string is executed as code (eval / new Function / exec) and user input can reach it.",
    ],
    impact: ["تنفيذ أوامر عشوائية داخل الخادم باسم التطبيق.", "Arbitrary code execution on the server as the application."],
    recommendation: ["استبدل eval بتحليل صريح أو مكتبة تحليل، وتحقق من أي مدخل يُمرَّر.", "Replace eval with explicit parsing or a parser library, and validate anything passed to it."],
    detection: ["نداءات AST/نصّية لـ eval/new Function/exec", "AST and textual calls to eval/new Function/exec"],
    references: [CWE(95), OWASP],
  }),
  def({
    id: "SEC-102",
    engine: "security",
    category: "security",
    severity: "HIGH",
    confidence: 0.8,
    languages: ["javascript", "typescript", "python", "php", "ruby", "go"],
    title: ["احتمال حقن أوامر (Command Injection)", "Possible command injection"],
    description: [
      "تنفيذ أمر نظام مع بناء النص من متغير — قد يحتوي على مدخل غير موثوق.",
      "A system command is built from a variable that may contain untrusted input.",
    ],
    impact: ["تنفيذ أوامر على الخادم: قراءة ملفات، حذف بيانات، أو pivot للشبكة الداخلية.", "Command execution on the host: file reads, data loss, or a pivot into the internal network."],
    recommendation: ["استخدم واجهات بلا shell ومرّر الوسائط كمصفوفة، وتحقق من المدخل بقائمة بيضاء.", "Use shell-free APIs with an argument array, and validate input against an allow-list."],
    detection: ["دوال shell + تسلسل نصي مع متغير", "Shell functions plus string concatenation with a variable"],
    references: [CWE(78)],
  }),
  def({
    id: "SEC-103",
    engine: "security",
    category: "security",
    severity: "HIGH",
    confidence: 0.78,
    languages: ["javascript", "typescript", "python", "php", "ruby", "java", "csharp"],
    title: ["بناء استعلام SQL بنص متغيّر", "SQL query built from a variable"],
    description: [
      "استعلام SQL يُبنى بدمج النص مع متغير بدل استخدام معاملات مربوطة.",
      "A SQL query concatenates or interpolates a variable instead of using bound parameters.",
    ],
    impact: ["حقن SQL: قراءة أو تعديل بيانات لا يملك المستخدم صلاحيتها.", "SQL injection: reading or modifying data the user is not authorised to touch."],
    recommendation: ["استخدم استعلامات مُعامَلة (prepared statements) ولا تدمج المدخل أبدًا.", "Use prepared statements with bound parameters; never interpolate input."],
    detection: ["بناء استعلام + متغير أو Template Literal", "Query construction plus a variable or template literal"],
    references: [CWE(89), OWASP],
  }),
  def({
    id: "SEC-104",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.75,
    languages: ["javascript", "typescript", "php", "ruby"],
    title: ["إدراج HTML خام (خطر XSS)", "Raw HTML injection (XSS risk)"],
    description: [
      "يُدرج HTML خام في الواجهة عبر dangerouslySetInnerHTML أو innerHTML أو v-html.",
      "Raw HTML is injected into the UI via dangerouslySetInnerHTML, innerHTML or v-html.",
    ],
    impact: ["تنفيذ سكربت في متصفح المستخدم وسرقة جلسته.", "Script execution in a user's browser and session theft."],
    recommendation: ["أعِد النص كقيمة نصية، أو نظّفه بمكتبة تنقية قبل الإدراج.", "Render the value as text, or sanitise it with a well-known library first."],
    detection: ["نداءات إدراج HTML خام", "Raw-HTML injection call sites"],
    references: [CWE(79)],
  }),
  def({
    id: "SEC-105",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.65,
    languages: ["javascript", "typescript", "python", "php", "go", "java"],
    title: ["احتمال تجاوز المسار (Path Traversal)", "Possible path traversal"],
    description: [
      "يُبنى مسار ملف من مدخل قد يحتوي على ../ أو مسار مطلق.",
      "A file path is built from input that may contain ../ or an absolute path.",
    ],
    impact: ["قراءة أو كتابة ملفات خارج مجلد التطبيق.", "Reading or writing files outside the application directory."],
    recommendation: ["طبّع المسار وتأكد أنه داخل المجلد المسموح، وارفض المسارات المطلقة.", "Normalise the path, verify it stays inside the allowed directory, and reject absolute paths."],
    detection: ["دوال قراءة/كتابة ملفات + دمج متغير", "File read/write functions combined with a variable"],
    references: [CWE(22)],
  }),
  def({
    id: "SEC-106",
    engine: "security",
    category: "security",
    severity: "HIGH",
    confidence: 0.85,
    languages: ["python", "php", "ruby", "java"],
    title: ["فك تسلسل غير آمن للبيانات", "Unsafe deserialisation"],
    description: [
      "فك تسلسل بيانات غير موثوقة (pickle, unserialize, yaml.load بلا SafeLoader).",
      "Untrusted data is deserialised (pickle, unserialize, yaml.load without SafeLoader).",
    ],
    impact: ["تنفيذ كود عند فك التسلسل، وهو مسار هجوم معروف.", "Code execution during deserialisation, a well-known attack path."],
    recommendation: ["استخدم صيغًا آمنة (JSON) أو الأوضاع الآمنة (yaml.safe_load) وارفض المدخل الخارجي.", "Use safe formats (JSON) or safe modes (yaml.safe_load) and refuse external input."],
    detection: ["دوال فك تسلسل معروفة", "Known deserialisation entry points"],
    references: [CWE(502)],
  }),
  def({
    id: "SEC-107",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.8,
    languages: ["javascript", "typescript", "python", "php", "java", "csharp"],
    title: ["دالة تشفير ضعيفة لكلمة المرور", "Weak hashing used for passwords"],
    description: ["استخدام MD5/SHA1 لتجزئة كلمات المرور.", "MD5/SHA1 is used to hash passwords."],
    impact: ["كسر كلمات المرور بسرعة بقوائم جاهزة عند تسريب القاعدة.", "Passwords are cracked quickly from a leaked database."],
    recommendation: ["استخدم bcrypt/argon2/scrypt مع ملح عشوائي لكل مستخدم.", "Use bcrypt/argon2/scrypt with a per-user random salt."],
    detection: ["دوال تجزئة قديمة في سياق كلمات المرور", "Legacy hash functions in a password context"],
    references: [CWE(916)],
  }),
  def({
    id: "SEC-108",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.7,
    languages: ["javascript", "typescript", "python", "php", "java", "go"],
    title: ["مولّد أرقام غير آمن للتوكنات", "Non-cryptographic randomness for tokens"],
    description: ["استخدام Math.random/random.random لتوليد توكن أو كود تحقق.", "Math.random/random.random generates a token or verification code."],
    impact: ["إمكانية توقّع التوكن وتجاوز المصادقة.", "Tokens become predictable, allowing authentication bypass."],
    recommendation: ["استخدم crypto.randomUUID / secrets / SecureRandom.", "Use crypto.randomUUID / secrets / SecureRandom."],
    detection: ["مولّد عشوائي ضعيف في سياق أمني", "Weak RNG in a security context"],
    references: [CWE(338)],
  }),
  def({
    id: "SEC-109",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.6,
    languages: ["javascript", "typescript", "php", "python"],
    title: ["رفع ملفات بلا قيود واضحة", "File upload without clear restrictions"],
    description: [
      "معالج رفع ملفات لا يفحص النوع أو الحجم قبل التخزين.",
      "An upload handler stores files without checking type or size first.",
    ],
    impact: ["رفع ملفات تنفيذية أو ملفات ضخمة تستهلك التخزين.", "Executable files or oversized uploads can be stored."],
    recommendation: ["حدّد الأنواع المسموحة بالمحتوى لا بالاسم، وحدّد حجمًا أقصى، وامنع التنفيذ في مجلد التخزين.", "Validate allowed types by content, cap the size, and prevent execution in the storage folder."],
    detection: ["دوال رفع ملفات + غياب فحص النوع/الحجم", "Upload handlers without type or size checks"],
    references: [CWE(434)],
  }),
  def({
    id: "SEC-110",
    engine: "security",
    category: "security",
    severity: "HIGH",
    confidence: 0.85,
    languages: ["javascript", "typescript", "php", "python", "java"],
    title: ["CORS مفتوح للجميع مع بيانات الاعتماد", "Wildcard CORS with credentials"],
    description: ["إعداد CORS يسمح لأي أصل مع credentials: true.", "CORS is configured for any origin together with credentials: true."],
    impact: ["مواقع أخرى تقرأ بيانات المستخدم المُصادَق عليه.", "Other sites can read the authenticated user's data."],
    recommendation: ["استخدم قائمة أصول صريحة، وتجنّب الجمع بين * وcredentials.", "Use an explicit allow-list and never combine * with credentials."],
    detection: ["إعدادات CORS مع '*'", "CORS configuration containing '*'"],
    references: [CWE(942)],
  }),
  def({
    id: "SEC-111",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.75,
    languages: "all",
    title: ["وضع التصحيح مفعّل في إعدادات الإنتاج", "Debug mode enabled in production settings"],
    description: ["‏APP_DEBUG/DEBUG=true أو DEVELOPMENT=1 في إعدادات المشروع.", "APP_DEBUG/DEBUG=true or DEVELOPMENT=1 in the project configuration."],
    impact: ["كشف تفاصيل داخلية ومسارات وأسرار للمستخدمين.", "Internal details, paths and secrets leak to users."],
    recommendation: ["أوقف التصحيح في الإنتاج وفعّله بمتغير بيئة للتطوير فقط.", "Disable debug in production and enable it through a development-only variable."],
    detection: ["قيم إعدادات معروفة للتصحيح", "Well-known debug configuration values"],
    references: [CWE(489)],
  }),
  def({
    id: "SEC-112",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.7,
    languages: "all",
    title: ["تسجيل بيانات حساسة", "Sensitive data written to logs"],
    description: ["سجلّ يطبع كلمة مرور أو توكن أو بيانات بطاقة.", "A log statement prints a password, token or card data."],
    impact: ["الأسرار تُحفظ في السجلات وتظهر لكل من يقرأها.", "Secrets persist in logs and are readable by anyone with log access."],
    recommendation: ["أخفِ الحقول الحساسة قبل التسجيل أو امتنع عن تسجيل الكائن كاملًا.", "Mask sensitive fields before logging, or stop logging the whole object."],
    detection: ["دوال تسجيل مع حقول حساسة", "Logging calls with sensitive field names"],
    references: [CWE(532)],
  }),
  def({
    id: "SEC-113",
    engine: "security",
    category: "security",
    severity: "HIGH",
    confidence: 0.85,
    languages: ["javascript", "typescript", "python", "php", "go", "java"],
    title: ["إيقاف التحقق من شهادة TLS", "TLS certificate verification disabled"],
    description: ["إعداد يتجاهل التحقق من الشهادة (rejectUnauthorized:false, verify=False).", "A setting ignores certificate validation (rejectUnauthorized:false, verify=False)."],
    impact: ["هجوم رجل-في-الوسط يصبح ممكنًا على كل الاتصالات.", "Man-in-the-middle attacks become possible on every request."],
    recommendation: ["أزل الإعداد وأصلح شهادة الخادم أو أضف CA الموثوق.", "Remove the flag and fix the server certificate or trust the correct CA."],
    detection: ["خيارات عميل HTTP معروفة", "Known HTTP client options"],
    references: [CWE(295)],
  }),
  def({
    id: "SEC-114",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.65,
    languages: ["javascript", "typescript", "php", "python"],
    title: ["إعادة توجيه إلى عنوان من المدخل", "Redirect to a user-controlled target"],
    description: ["إعادة توجيه أو جلب رابط من مدخل المستخدم بلا قائمة تحقق.", "A redirect or fetch target comes from user input without validation."],
    impact: ["تصيّد عبر نطاقك، أو وصول لخدمات داخلية (SSRF).", "Phishing through your domain, or access to internal services (SSRF)."],
    recommendation: ["اسمح بقائمة مسارات داخلية فقط، وامنع العناوين الداخلية.", "Allow only a list of internal paths and block internal addresses."],
    detection: ["دوال إعادة التوجيه مع مدخل", "Redirect helpers combined with request input"],
    references: [CWE(601), CWE(918)],
  }),
  def({
    id: "SEC-115",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.7,
    languages: ["javascript", "typescript"],
    title: ["تخزين أسرار المتصفح في localStorage", "Browser secrets kept in localStorage"],
    description: ["توكن مصادقة يُخزَّن في localStorage بدل كوكي آمن.", "An auth token is stored in localStorage instead of a secure cookie."],
    impact: ["أي ثغرة XSS تسرق التوكن بسهولة.", "Any XSS immediately steals the token."],
    recommendation: ["استخدم كوكي httpOnly وSameSite مع جلسة على الخادم.", "Use an httpOnly, SameSite cookie backed by a server session."],
    detection: ["استدعاءات التخزين المحلي مع أسماء توكنات", "Local-storage calls with token-like keys"],
    references: [CWE(922)],
  }),
  def({
    id: "SEC-116",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.6,
    languages: ["python"],
    title: ["تنفيذ أمر shell=True", "subprocess executed with shell=True"],
    description: ["تشغيل عملية عبر shell مع نص مبني من متغير.", "A process runs through a shell with a string built from a variable."],
    impact: ["حقن أوامر عند تلويث أي جزء من النص.", "Command injection if any part of the string is tainted."],
    recommendation: ["استخدم قائمة وسائط مع shell=False.", "Pass an argument list with shell=False."],
    detection: ["وسائط subprocess/os.system", "subprocess/os.system arguments"],
    references: [CWE(78)],
  }),
  def({
    id: "SEC-117",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.7,
    languages: ["php"],
    title: ["حماية CSRF معطّلة", "CSRF protection disabled"],
    description: ["تعطيل حماية CSRF في إطار العمل (csrf_exempt أو ما يعادله).", "The framework's CSRF protection is disabled (csrf_exempt or similar)."],
    impact: ["طلب مزيّف من موقع آخر ينفّذ عملية باسم المستخدم.", "A forged request from another site performs an action as the user."],
    recommendation: ["أعد تفعيل الحماية أو وفّر تحققًا بديلًا للتوكن.", "Re-enable protection or provide equivalent token validation."],
    detection: ["وسوم تعطيل الحماية", "Disablement annotations"],
    references: [CWE(352)],
  }),
  def({
    id: "SEC-118",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.65,
    languages: ["php"],
    title: ["إسناد جماعي غير محمي", "Unprotected mass assignment"],
    description: ["نموذج مفتوح للتعديل الجماعي (‎$guarded = [] أو fillable واسع).", "A model is open to mass assignment ($guarded = [] or a very wide fillable list)."],
    impact: ["مستخدم يستطيع تعديل حقول حساسة مثل role أو is_admin.", "A user can modify sensitive fields such as role or is_admin."],
    recommendation: ["استخدم قائمة fillable صريحة واستبعد الحقول الحساسة.", "Use an explicit fillable list and exclude sensitive fields."],
    detection: ["خصائص النماذج في إطار العمل", "Framework model properties"],
    references: [CWE(915)],
  }),
  def({
    id: "SEC-119",
    engine: "security",
    category: "security",
    severity: "LOW",
    confidence: 0.6,
    languages: "all",
    title: ["تعليق يحتوي على كود معطّل", "Commented-out code left behind"],
    description: ["كود قديم معلَّق بجانب كود فعّال.", "Old code is commented out next to live code."],
    impact: ["صعوبة معرفة السلوك الصحيح، وقد يُحيي كودًا غير آمن لاحقًا.", "It becomes hard to know the real behaviour, and unsafe code may be revived later."],
    recommendation: ["احذفه — تاريخ Git يحفظه إن احتجته.", "Delete it — Git history keeps it if you need it."],
    detection: ["تعليقات تشبه كودًا في سياق دالة", "Code-like comments inside a function body"],
    references: [],
  }),
];
