import type { RuleDef } from "../../types";
import { CWE, OSV, OWASP, def } from "./shared";

/** Rules in the `dependencies` category. Order matters: it is the order the report prints. */
export const dependenciesRules: RuleDef[] = [
  def({
    id: "DEP-001",
    engine: "dependencies",
    category: "dependencies",
    severity: "HIGH",
    confidence: 0.95,
    languages: "all",
    title: ["تبعية مصابة بثغرة معروفة", "Dependency with a known vulnerability"],
    description: ["حزمة مستخدمة في المشروع لها تحذير أمني منشور.", "A package used by the project has a published security advisory."],
    impact: ["الثغرة قابلة للاستغلال من خارج النظام مباشرة.", "The vulnerability is directly reachable from outside the system."],
    recommendation: ["حدّث الحزمة إلى الإصدار المُصلِح المذكور في التحذير.", "Upgrade the package to the fixed version listed in the advisory."],
    detection: ["مطابقة الإصدارات مع قاعدة OSV", "Version matching against the OSV database"],
    references: [OSV],
  }),
  def({
    id: "DEP-002",
    engine: "dependencies",
    category: "dependencies",
    severity: "LOW",
    confidence: 0.85,
    languages: "all",
    title: ["إصدار تبعية غير مثبَّت", "Dependency version is not pinned"],
    description: ["الحزمة مطلوبة بنطاق مفتوح أو latest بدل إصدار محدد.", "The package is requested with an open range or latest instead of a fixed version."],
    impact: ["تحديث غير متوقع قد يكسر المشروع أو يُدخل كودًا غير مراجَع.", "An unexpected update can break the build or pull in unreviewed code."],
    recommendation: ["ثبّت الإصدار (exact) أو استخدم lock file وأبقِه في المستودع.", "Pin the exact version, or keep a lock file committed in the repository."],
    detection: ["قراءة بادئات النطاقات في ملفات الحزم", "Range prefixes in package manifests"],
    references: [],
  }),
  def({
    id: "DEP-003",
    engine: "dependencies",
    category: "dependencies",
    severity: "LOW",
    confidence: 0.75,
    languages: "all",
    title: ["حزمة متأخرة عن أحدث إصدار رئيسي", "Package far behind the latest release"],
    description: ["النسخة المثبّتة أقدم بكثير من أحدث إصدار منشور.", "The pinned version is well behind the latest published release."],
    impact: ["إصلاحات الأمان والتحسينات غير موجودة في مشروعك.", "Security fixes and improvements are missing from your project."],
    recommendation: ["خطّط ترقية تدريجية مع اختبارات قبل الدمج.", "Plan a staged upgrade with tests before merging."],
    detection: ["مقارنة الإصدار بأحدث إصدار من السجل العام", "Version compared with the latest published release"],
    references: [],
  }),
  def({
    id: "DEP-004",
    engine: "dependencies",
    category: "dependencies",
    severity: "INFO",
    confidence: 1,
    languages: "all",
    title: ["تعذّر التحقق من التبعيات", "Dependency verification unavailable"],
    description: ["لم يتم الاتصال بقاعدة التحذيرات، فلم تُفحص هذه التبعيات (لا يعني أنها سليمة).", "The advisory database could not be reached, so these dependencies were not checked (this does not mean they are clean)."],
    impact: ["غياب نتيجة ليس دليلًا على السلامة.", "A missing result is not proof of safety."],
    recommendation: ["أعد التدقيق لاحقًا أو استخدم أداة فحص محليًا.", "Re-run the audit later or scan locally with your own tool."],
    detection: ["تسجيل حالة الاتصال بمصدر التحذيرات", "Recorded status of the advisory source"],
    references: [OSV],
  }),
];
