import type { RuleDef } from "../../types";
import { CWE, OSV, OWASP, def } from "./shared";

/** Rules in the `quality` category. Order matters: it is the order the report prints. */
export const qualityRules: RuleDef[] = [
  def({
    id: "QUA-001",
    engine: "quality",
    category: "quality",
    severity: "LOW",
    confidence: 0.95,
    languages: ["javascript", "typescript", "python", "php", "java", "csharp", "go", "ruby"],
    title: ["دالة طويلة جدًا", "Function is very long"],
    description: ["طول الدالة يتجاوز الحد المتفق عليه (60 سطرًا).", "The function body exceeds the agreed limit (60 lines)."],
    impact: ["صعوبة المراجعة والاختبار وزيادة احتمال الأخطاء.", "Harder to review and test, and more likely to hide defects."],
    recommendation: ["قسّم الدالة إلى خطوات صغيرة بأسماء واضحة.", "Split the function into small, well-named steps."],
    detection: ["قياس أسطر جسم الدالة", "Measuring function body lines"],
    references: [],
  }),
  def({
    id: "QUA-002",
    engine: "quality",
    category: "quality",
    severity: "MEDIUM",
    confidence: 0.9,
    languages: ["javascript", "typescript", "python", "php", "java", "csharp", "go", "ruby"],
    title: ["تعقيد دوري مرتفع", "High cyclomatic complexity"],
    description: ["عدد مسارات التنفيذ في الدالة كبير (أكثر من 15).", "The number of execution paths in the function is high (over 15)."],
    impact: ["عدد الحالات التي يجب اختبارها كبير، والمنطق صعب التتبع.", "Many cases need testing and the logic is hard to follow."],
    recommendation: ["استخرج الشروط المتكررة إلى دوال، واستبدل الفروع المتشابكة بجدول قرار.", "Extract repeated conditions into functions and replace nested branches with a decision table."],
    detection: ["عدّ الفروع والحلقات في الـAST", "Counting branches and loops in the AST"],
    references: [],
  }),
  def({
    id: "QUA-003",
    engine: "quality",
    category: "quality",
    severity: "LOW",
    confidence: 0.8,
    languages: "all",
    title: ["كتلة كود مكررة", "Duplicated code block"],
    description: ["كتلة من الأسطر المتطابقة (بعد التطبيع) تتكرر في أكثر من موضع.", "A block of identical lines (after normalisation) appears in more than one place."],
    impact: ["إصلاح الخلل في نسخة واحدة يترك الأخرى مكسورة.", "Fixing a bug in one copy leaves the other broken."],
    recommendation: ["استخرج الكتلة المشتركة إلى دالة أو وحدة مشتركة.", "Extract the shared block into one function or module."],
    detection: ["تجزئة نوافذ أسطر مُطبَّعة ومقارنتها", "Hashing normalised line windows and comparing them"],
    references: [],
  }),
  def({
    id: "QUA-004",
    engine: "quality",
    category: "quality",
    severity: "MEDIUM",
    confidence: 0.85,
    languages: ["javascript", "typescript", "python", "php", "java", "csharp", "dart"],
    title: ["خطأ مُبتلَع بدون معالجة", "Error swallowed without handling"],
    description: ["كتلة catch فارغة أو تتجاهل الخطأ بلا تسجيل ولا معالجة.", "An empty catch block ignores the error without logging or handling."],
    impact: ["تفشل العمليات بصمت ويستحيل تشخيص المشكلة في الإنتاج.", "Operations fail silently and production issues become undiagnosable."],
    recommendation: ["سجّل الخطأ مع سياقه، أو أعد رميه بعد تغليفه برسالة واضحة.", "Log the error with context, or rethrow it wrapped with a clear message."],
    detection: ["كتل catch بلا تعليمات", "Catch blocks with an empty body"],
    references: [],
  }),
  def({
    id: "QUA-005",
    engine: "quality",
    category: "quality",
    severity: "LOW",
    confidence: 0.9,
    languages: "all",
    title: ["ملف كبير جدًا", "Oversized source file"],
    description: ["الملف يتجاوز 600 سطر منطقي.", "The file exceeds 600 logical lines."],
    impact: ["الملف يجمع مسؤوليات كثيرة ويصعب مراجعته.", "The file mixes many responsibilities and is hard to review."],
    recommendation: ["افصل الأنواع والدوال ذات المسؤولية الواحدة إلى ملفات.", "Split types and functions into files with a single responsibility."],
    detection: ["عدّ الأسطر المنطقية لكل ملف", "Counting logical lines per file"],
    references: [],
  }),
  def({
    id: "QUA-006",
    engine: "quality",
    category: "quality",
    severity: "LOW",
    confidence: 0.85,
    languages: ["javascript", "typescript", "python", "php", "java", "csharp", "go", "dart"],
    title: ["عدد وسائط كبير", "Function takes too many parameters"],
    description: ["الدالة تستقبل أكثر من 6 وسائط.", "The function accepts more than 6 parameters."],
    impact: ["احتمال تبديل الوسائط عند الاستدعاء وارد جدًا.", "Arguments are easily passed in the wrong order."],
    recommendation: ["اجمع الوسائط في كائن/بنية واضحة.", "Group the parameters into a single options object or struct."],
    detection: ["عدّ وسائط تعريف الدالة", "Counting declared function parameters"],
    references: [],
  }),
  def({
    id: "QUA-007",
    engine: "quality",
    category: "quality",
    severity: "LOW",
    confidence: 0.8,
    languages: ["javascript", "typescript", "python", "php", "java", "csharp", "dart"],
    title: ["تداخل شروط عميق", "Deeply nested conditions"],
    description: ["مستوى التداخل داخل الدالة يتجاوز 5 مستويات.", "Nesting inside the function goes deeper than 5 levels."],
    impact: ["صعوبة تتبع المسار المنطقي وارتفاع احتمال الخطأ.", "The control flow is hard to follow and error-prone."],
    recommendation: ["استخدم الحماية المبكرة (early return) وأخرج الشروط إلى دوال.", "Use early returns and extract conditions into named functions."],
    detection: ["قياس أقصى عمق للكتل في الـAST", "Measuring maximum block depth in the AST"],
    references: [],
  }),
  def({
    id: "QUA-008",
    engine: "quality",
    category: "quality",
    severity: "INFO",
    confidence: 0.95,
    languages: "all",
    title: ["تعليق مؤجَّل (TODO/FIXME/HACK)", "Unfinished-work comment (TODO/FIXME/HACK)"],
    description: ["تعليق يسجّل عملًا مؤجلًا أو حلًا مؤقتًا.", "A comment records deferred work or a temporary workaround."],
    impact: ["دَين تقني غير متتبع، وأحيانًا مشكلة أمنية معروفة مؤجّلة.", "Untracked technical debt — sometimes a known security issue postponed."],
    recommendation: ["حوّل التعليق إلى مهمة متتبَّعة، أو أزل التعليق بعد الحل.", "Turn the comment into a tracked task, or remove it once resolved."],
    detection: ["وسوم تعليقات معروفة", "Well-known comment markers"],
    references: [],
  }),
  def({
    id: "QUA-009",
    engine: "quality",
    category: "quality",
    severity: "INFO",
    confidence: 0.9,
    languages: ["javascript", "typescript", "php", "dart"],
    title: ["طباعة تشخيصية في كود الإنتاج", "Diagnostic logging left in production code"],
    description: ["نداء console.log/debug في كود غير اختباري.", "A console.log/debug call sits in non-test code."],
    impact: ["تلويث السجلات وإمكانية تسريب بيانات.", "Noisy logs and possible data leakage."],
    recommendation: ["استخدم مكتبة تسجيل بمستويات، واحذف الطبعات المؤقتة.", "Use a levelled logger and remove temporary prints."],
    detection: ["عدّ نداءات الطباعة لكل ملف", "Counting print calls per file"],
    references: [],
  }),
  def({
    id: "QUA-010",
    engine: "quality",
    category: "quality",
    severity: "LOW",
    confidence: 0.9,
    languages: ["typescript"],
    title: ["إسكات فحص الأنواع", "Type checking silenced"],
    description: ["استخدام ts-ignore/ts-expect-error/any واسع لتعطيل فحص الأنواع.", "ts-ignore/ts-expect-error or a broad any disables type checking."],
    impact: ["الأخطاء التي كان سيكشفها المترجم تصل إلى الإنتاج.", "Errors the compiler would have caught reach production."],
    recommendation: ["استبدل الإسكات بنوع صريح أو تحقق يدوي من المدخل.", "Replace the suppression with an explicit type or a runtime check."],
    detection: ["وسوم الإسكات واستخدامات any", "Suppression comments and any usages"],
    references: [],
  }),
];
