import type { RuleDef } from "../../types";
import { CWE, OSV, OWASP, def } from "./shared";

/** Rules in the `architecture` category. Order matters: it is the order the report prints. */
export const architectureRules: RuleDef[] = [
  def({
    id: "ARC-001",
    engine: "architecture",
    category: "architecture",
    severity: "MEDIUM",
    confidence: 0.9,
    languages: "all",
    title: ["اعتمادية دائرية بين الوحدات", "Circular dependency between modules"],
    description: ["وحدة تستورد وحدة تستورد الأولى، مباشرة أو عبر سلسلة.", "A module imports another that imports it back, directly or through a chain."],
    impact: ["ترتيب التحميل غير متوقع، وصعوبة اختبار الوحدات منفصلة.", "Load order becomes unpredictable and modules cannot be tested in isolation."],
    recommendation: ["افصل الجزء المشترك في وحدة ثالثة، أو اعكس الاعتماد بواجهة.", "Extract the shared part into a third module, or invert the dependency behind an interface."],
    detection: ["رسم اعتماديات الاستيراد ثم كشف الحلقات", "Import graph construction followed by cycle detection"],
    references: [],
  }),
  def({
    id: "ARC-002",
    engine: "architecture",
    category: "architecture",
    severity: "LOW",
    confidence: 0.75,
    languages: "all",
    title: ["وحدة عالية الارتباط", "Highly coupled module"],
    description: ["وحدة تستورد عددًا كبيرًا من الوحدات أو يعتمد عليها عدد كبير.", "A module imports many others, or many others depend on it."],
    impact: ["أي تغيير صغير ينتشر في المشروع كله.", "A small change ripples across the whole project."],
    recommendation: ["قسّم الوحدة على مسؤوليات أو أدخل واجهة وسيطة.", "Split the module by responsibility or introduce a mediating interface."],
    detection: ["حساب fan-in/fan-out ومؤشر عدم الاستقرار", "Computing fan-in/fan-out and an instability index"],
    references: [],
  }),
  def({
    id: "ARC-003",
    engine: "architecture",
    category: "architecture",
    severity: "MEDIUM",
    confidence: 0.65,
    languages: ["javascript", "typescript"],
    title: ["واجهة الواجهة الأمامية تستورد طبقة البيانات", "Front-end code imports the data layer directly"],
    description: ["ملف واجهة (component/page) يستورد مشغّل قاعدة بيانات أو استعلامًا مباشرًا.", "A UI file (component/page) imports a database driver or a direct query."],
    impact: ["منطق البيانات يتسرب للواجهة، ويصبح من الصعب تأمين الصلاحيات وتغيير الطبقة.", "Data logic leaks into the UI, and authorisation plus refactoring become harder."],
    recommendation: ["اجعل الواجهة تنادي API فقط، واترك الوصول للبيانات في الخادم.", "Have the UI call an API only, and keep data access on the server."],
    detection: ["مسار الملف + حزمة مستوردة معروفة لقواعد البيانات", "File path plus a known database import"],
    references: [],
  }),
  def({
    id: "ARC-004",
    engine: "architecture",
    category: "architecture",
    severity: "LOW",
    confidence: 0.85,
    languages: "all",
    title: ["وحدة ضخمة تجمع مسؤوليات", "Oversized module"],
    description: ["وحدة تتجاوز 800 سطر منطقي.", "A module exceeds 800 logical lines."],
    impact: ["الوحدة تصبح نقطة تغيير دائمة وسببًا للتعارضات.", "The module becomes a permanent change hotspot and a merge-conflict source."],
    recommendation: ["فكّك الوحدة حسب حالات الاستخدام، وابدأ بأكثر الأجزاء تغيّرًا.", "Break the module down by use case, starting with the parts that change most."],
    detection: ["حساب الأسطر المنطقية لكل وحدة", "Logical line count per module"],
    references: [],
  }),
];
