import type { RuleDef } from "../../types";
import { CWE, OSV, OWASP, def } from "./shared";

/** Rules in the `api` category. Order matters: it is the order the report prints. */
export const apiRules: RuleDef[] = [
  def({
    id: "API-001",
    engine: "api",
    category: "api",
    severity: "HIGH",
    confidence: 0.6,
    languages: ["javascript", "typescript", "php", "python", "ruby", "java", "csharp", "go"],
    title: ["مسار يغيّر البيانات بلا إشارة تصريح", "Mutating route with no authorisation signal"],
    description: [
      "مسار POST/PUT/PATCH/DELETE لا يظهر في جسمه أي فحص مصادقة أو ملكية أو دور.",
      "A POST/PUT/PATCH/DELETE route shows no authentication, ownership or role check in its handler.",
    ],
    impact: ["قد يسمح لمستخدم بتغيير بيانات لا يملكها — يحتاج تأكيدًا من الفريق.", "A user may be able to modify data they do not own — this needs team confirmation."],
    recommendation: ["أضف فحص مصادقة ثم فحص ملكية/دور قبل أي تعديل، وسجّل سياسة صريحة.", "Add an authentication check followed by an ownership/role check before mutating, with an explicit policy."],
    detection: ["استخراج جسم المعالج والبحث عن دوال/وسائط تصريح", "Handler body extraction followed by a search for auth/policy constructs"],
    references: [CWE(862), OWASP],
  }),
  def({
    id: "API-002",
    engine: "api",
    category: "api",
    severity: "MEDIUM",
    confidence: 0.6,
    languages: ["javascript", "typescript", "php", "python", "ruby"],
    title: ["مسار يستخدم مدخل الطلب بلا تحقق ظاهر", "Route uses request input without visible validation"],
    description: ["قيم الطلب تُستخدم مباشرة في الاستعلام أو الحفظ بلا مخطط تحقق.", "Request values flow straight into a query or write without a validation schema."],
    impact: ["مدخلات غير متوقعة تسبب أخطاء أو كتابة بيانات غير صالحة.", "Unexpected input causes errors or stores invalid data."],
    recommendation: ["تحقق بمخطط (zod/Joi/FormRequest/Serializer) عند حدود النظام.", "Validate with a schema (zod/Joi/FormRequest/Serializer) at the system boundary."],
    detection: ["استخدام req.body/request.data مع غياب مخطط تحقق", "Use of req.body/request.data without a validation schema"],
    references: [CWE(20)],
  }),
  def({
    id: "API-003",
    engine: "api",
    category: "api",
    severity: "MEDIUM",
    confidence: 0.7,
    languages: ["javascript", "typescript", "php", "python", "ruby", "java"],
    title: ["كشف تفاصيل داخلية في رسالة الخطأ", "Internal details exposed in error responses"],
    description: ["استجابة الخطأ تحتوي stack trace أو رسالة النظام الأصلية.", "An error response exposes a stack trace or the raw system message."],
    impact: ["يكشف بنية المشروع والمسارات وإصدارات المكتبات للمهاجم.", "It reveals project structure, paths and library versions to an attacker."],
    recommendation: ["أعِد رسالة عامة مع معرّف تتبع، واحتفظ بالتفاصيل في السجل.", "Return a generic message with a trace id, and keep details in the logs."],
    detection: ["إرجاع error.message/stack في الاستجابة", "Returning error.message/stack in the response"],
    references: [CWE(209)],
  }),
  def({
    id: "API-004",
    engine: "api",
    category: "api",
    severity: "LOW",
    confidence: 0.55,
    languages: "all",
    title: ["مسارات مصادقة بلا إشارة تحديد معدل", "Auth routes with no rate-limit signal"],
    description: ["مسارات الدخول/التسجيل/التحقق لا تُظهر أي تحديد معدل الطلبات.", "Login/registration/verification routes show no request throttling."],
    impact: ["تخمين كلمات المرور أو إغراق الطلبات يصبح أسهل.", "Password guessing or request flooding becomes easier."],
    recommendation: ["أضف Middleware لتحديد المعدل مع تسجيل المحاولات الفاشلة.", "Add rate-limiting middleware and record failed attempts."],
    detection: ["مسارات المصادقة + غياب وسيط التحديد", "Auth routes without throttling middleware"],
    references: [CWE(307)],
  }),
  def({
    id: "API-005",
    engine: "api",
    category: "api",
    severity: "HIGH",
    confidence: 0.7,
    languages: ["javascript", "typescript", "php", "python", "ruby"],
    title: ["إرجاع كائن المستخدم كاملًا (بما فيه كلمة المرور)", "Returning a full user object including credentials"],
    description: ["استجابة تعيد الكائن كاملًا مع حقول مثل password أو token أو secret.", "A response returns the whole object including fields such as password, token or secret."],
    impact: ["تسريب بيانات اعتماد عبر API يمكن استغلاله مباشرة.", "Credential leakage through an API that can be used directly."],
    recommendation: ["استخدم DTO/Resource وحدّد الحقول المسموحة في الاستجابة.", "Use a DTO/Resource and whitelist the fields returned."],
    detection: ["إرجاع كائن + اختيار حقول حساسة أو select *", "Object returned alongside sensitive field selection or select *"],
    references: [CWE(213)],
  }),
  def({
    id: "API-006",
    engine: "api",
    category: "api",
    severity: "LOW",
    confidence: 0.6,
    languages: ["javascript", "typescript", "php", "python", "ruby"],
    title: ["قائمة بلا ترقيم صفحات", "List endpoint without pagination"],
    description: ["مسار يعيد قائمة كاملة بلا limit/offset أو cursor.", "A route returns a full list without limit/offset or a cursor."],
    impact: ["استجابة ضخمة وبطء تدريجي مع نمو البيانات.", "A heavy response that degrades as data grows."],
    recommendation: ["أضف ترقيمًا بحد أقصى واضح واستعلامًا مقيّدًا.", "Add pagination with a sane maximum and a bounded query."],
    detection: ["دوال البحث/الجلب التي تعيد كل السجلات", "Find/all calls that return every record"],
    references: [],
  }),
];
