import type { RuleDef } from "../../types";
import { CWE, OSV, OWASP, def } from "./shared";

/** Rules in the `database` category. Order matters: it is the order the report prints. */
export const databaseRules: RuleDef[] = [
  def({
    id: "DBN-001",
    engine: "database",
    category: "database",
    severity: "MEDIUM",
    confidence: 0.7,
    languages: "all",
    title: ["عمود مفتاح أجنبي بلا فهرس", "Foreign key column without an index"],
    description: ["مخطط الجداول يعرّف مفتاحًا أجنبيًا بلا فهرس صريح عليه.", "The schema defines a foreign key with no explicit index on the column."],
    impact: ["استعلامات الربط تصبح بطيئة جدًا مع نمو البيانات.", "Join queries slow down badly as data grows."],
    recommendation: ["أضف فهرسًا على عمود المفتاح الأجنبي في ترحيل جديد.", "Add an index on the foreign key column in a new migration."],
    detection: ["تحليل ملفات الترحيلات/المخطط", "Parsing migration and schema files"],
    references: [],
  }),
  def({
    id: "DBN-002",
    engine: "database",
    category: "database",
    severity: "LOW",
    confidence: 0.6,
    languages: "all",
    title: ["عمود يمثل هوية بلا قيد تفرّد", "Identity-like column without a unique constraint"],
    description: ["عمود مثل email/username/phone بلا فهرس فريد.", "A column such as email/username/phone has no unique constraint."],
    impact: ["إمكانية تسجيل بيانات مكررة وتناقضها لاحقًا.", "Duplicate records can be created and diverge later."],
    recommendation: ["أضف قيد UNIQUE بعد تنظيف البيانات المكررة الحالية.", "Add a UNIQUE constraint after cleaning existing duplicates."],
    detection: ["أسماء أعمدة معروفة + غياب unique", "Known column names without a unique constraint"],
    references: [],
  }),
  def({
    id: "DBN-003",
    engine: "database",
    category: "database",
    severity: "MEDIUM",
    confidence: 0.65,
    languages: ["javascript", "typescript", "php", "python", "ruby", "java"],
    title: ["نمط N+1 محتمل", "Possible N+1 query pattern"],
    description: ["استعلام قاعدة بيانات داخل حلقة أو map على مجموعة نتائج.", "A database call sits inside a loop or a map over results."],
    impact: ["عدد الاستعلامات ينمو مع عدد الصفوف، ويتدهور الأداء بسرعة.", "Queries grow with row count and performance degrades quickly."],
    recommendation: ["استخدم eager loading أو استعلامًا واحدًا بدمج، أو أجّل التنفيذ على دفعات.", "Use eager loading or a single join, or batch the work."],
    detection: ["نداء قاعدة بيانات داخل كتلة تكرار", "Database call detected inside an iteration block"],
    references: [],
  }),
  def({
    id: "DBN-004",
    engine: "database",
    category: "database",
    severity: "LOW",
    confidence: 0.7,
    languages: ["javascript", "typescript", "php", "python", "ruby", "java"],
    title: ["استعلام يجلب كل الأعمدة", "Query selecting every column"],
    description: ["استعلام يستخدم SELECT * بدل تحديد الأعمدة المطلوبة.", "A query uses SELECT * instead of naming the needed columns."],
    impact: ["بيانات حساسة قد تُقرأ بلا داعٍ، وأداء أقل مع الجداول الكبيرة.", "Sensitive data may be read unnecessarily, with worse performance on wide tables."],
    recommendation: ["حدّد الأعمدة المطلوبة صريحًا.", "Name the required columns explicitly."],
    detection: ["أنماط SELECT * في الاستعلامات", "SELECT * patterns in queries"],
    references: [],
  }),
  def({
    id: "DBN-005",
    engine: "database",
    category: "database",
    severity: "LOW",
    confidence: 0.8,
    languages: "all",
    title: ["ترحيل يُسقط جدولًا أو عمودًا", "Migration drops a table or column"],
    description: ["ترحيل جديد يحذف جدولًا أو عمودًا — لا رجعة بعد التنفيذ.", "A new migration drops a table or column — it cannot be undone after running."],
    impact: ["فقدان بيانات غير قابل للاستعادة إن لم يكن منسوخًا مسبقًا.", "Unrecoverable data loss if no backup was taken first."],
    recommendation: ["انقل البيانات أولًا، ونفّذ الإسقاط في ترحيل لاحق بعد التأكد ونسخة احتياطية.", "Migrate the data first, then drop in a later migration once verified and backed up."],
    detection: ["عبارات drop/delete في ملفات الترحيلات", "drop/delete statements in migration files"],
    references: [],
  }),
];
