import type { RuleDef } from "../../types";
import { CWE, OSV, OWASP, def } from "./shared";

/** Rules in the `ops` category. Order matters: it is the order the report prints. */
export const opsRules: RuleDef[] = [
  def({
    id: "OPS-001",
    engine: "ops",
    category: "ops",
    severity: "MEDIUM",
    confidence: 0.8,
    languages: "all",
    title: ["الحاوية تعمل بصلاحيات root", "Container runs as root"],
    description: ["ملف Dockerfile لا يحدد مستخدمًا غير root (USER).", "The Dockerfile never switches to a non-root USER."],
    impact: ["أي اختراق داخل الحاوية يقترب من صلاحيات المضيف.", "Any compromise inside the container gets closer to host privileges."],
    recommendation: ["أنشئ مستخدمًا محدودًا وبدّل إليه قبل CMD.", "Create an unprivileged user and switch to it before CMD."],
    detection: ["تحليل تعليمات Dockerfile", "Dockerfile instruction analysis"],
    references: ["https://docs.docker.com/develop/develop-images/dockerfile_best-practices/"],
  }),
  def({
    id: "OPS-002",
    engine: "ops",
    category: "ops",
    severity: "LOW",
    confidence: 0.85,
    languages: "all",
    title: ["صورة أساس غير مثبَّتة الإصدار", "Unpinned base image"],
    description: ["‏FROM يستخدم latest أو بلا إصدار محدد.", "FROM uses latest or no fixed version."],
    impact: ["بناء متغيّر بلا تحكّم، وقد يتغير فجأة بين نشرين.", "Uncontrolled builds that can change between deployments."],
    recommendation: ["ثبّت وسوم إصدار محددة أو hash للصورة.", "Pin explicit version tags or an image digest."],
    detection: ["وسوم صور Dockerfile", "Dockerfile image tags"],
    references: [],
  }),
  def({
    id: "OPS-003",
    engine: "ops",
    category: "ops",
    severity: "HIGH",
    confidence: 0.85,
    languages: "all",
    title: ["تنفيذ سكربت بعيد أثناء البناء", "Remote script executed during build"],
    description: ["‏RUN ينفّذ curl|bash أو تحميلًا مباشرًا من الإنترنت.", "A RUN step pipes curl into bash or downloads and runs remote code."],
    impact: ["بناء غير قابل للتتبع قد يحمل كودًا خبيثًا.", "An untraceable build that may pull in malicious code."],
    recommendation: ["نزّل بإصدار وhash محددين وتحقق من التوقيع.", "Download with a pinned version and verify a checksum or signature."],
    detection: ["أنماط تنزيل وتنفيذ في Dockerfile", "Download-and-execute patterns in Dockerfiles"],
    references: [],
  }),
  def({
    id: "OPS-004",
    engine: "ops",
    category: "ops",
    severity: "HIGH",
    confidence: 0.85,
    languages: "all",
    title: ["أسرار مكتوبة في ملفات CI", "Secrets written into CI workflow files"],
    description: ["سير عمل CI يحمل قيمًا سرية كنص صريح بدل متغيرات محمية.", "A CI workflow contains literal secret values instead of protected variables."],
    impact: ["الأسرار متاحة لكل من يقرأ سير العمل أو سجلاته.", "Secrets are readable by anyone who can view the workflow or its logs."],
    recommendation: ["استخدم أسرار المنصة (Secrets) عبر متغيرات، وأبطِل القيم المكشوفة.", "Use the platform's secret store via variables, and revoke the exposed values."],
    detection: ["مفاتيح YAML معروفة في ملفات CI", "Known YAML keys inside CI files"],
    references: [CWE(798)],
  }),
  def({
    id: "OPS-005",
    engine: "ops",
    category: "ops",
    severity: "HIGH",
    confidence: 0.8,
    languages: "all",
    title: ["حاوية بصلاحيات موسّعة", "Privileged container configuration"],
    description: ["إعداد privileged أو host network يمنح الحاوية صلاحيات المضيف.", "A privileged or host-network setting grants host-level access."],
    impact: ["اختراق الحاوية يعني اختراق المضيف والشبكة.", "A container compromise becomes a host and network compromise."],
    recommendation: ["أزل التعليمات، وحدّد القدرات والشبكات بأقل صلاحية.", "Remove it and grant only the capabilities and networks actually needed."],
    detection: ["خيارات privileged/host في Docker وdocker-compose", "privileged/host options in Docker and docker-compose"],
    references: [],
  }),
  def({
    id: "OPS-006",
    engine: "ops",
    category: "ops",
    severity: "INFO",
    confidence: 0.9,
    languages: "all",
    title: ["لا يوجد .dockerignore", "No .dockerignore"],
    description: ["بناء الحاوية ينسخ كل شيء بما فيه node_modules وملفات الأسرار.", "The build context includes everything, including node_modules and secret files."],
    impact: ["صور أكبر وتسريب محتمل لملفات حساسة داخل الطبقات.", "Larger images and possible leakage of sensitive files into layers."],
    recommendation: ["أضف .dockerignore يستبعد .git وnode_modules و*.env.", "Add a .dockerignore excluding .git, node_modules and *.env."],
    detection: ["وجود Dockerfile مع غياب .dockerignore", "Dockerfile present without .dockerignore"],
    references: [],
  }),
  def({
    id: "OPS-007",
    engine: "ops",
    category: "ops",
    severity: "INFO",
    confidence: 0.95,
    languages: "all",
    title: ["لا يوجد .gitignore", "No .gitignore"],
    description: ["المستودع بلا ملف .gitignore.", "The repository has no .gitignore file."],
    impact: ["رفع ملفات أسرار أو مخرجات بناء بالخطأ وارد جدًا.", "Secret files or build output are easily committed by mistake."],
    recommendation: ["أضف .gitignore يستبعد الأسرار والمخرجات والتغطية.", "Add a .gitignore covering secrets, build output and coverage."],
    detection: ["غياب ملف .gitignore", "Absence of the .gitignore file"],
    references: [],
  }),
];
