import type { RuleDef } from "../../types";
import { CWE, OSV, OWASP, def } from "./shared";

/** Rules in the `tests` category. Order matters: it is the order the report prints. */
export const testsRules: RuleDef[] = [
  def({
    id: "TST-001",
    engine: "tests",
    category: "tests",
    severity: "MEDIUM",
    confidence: 0.9,
    languages: "all",
    title: ["لا اختبارات في المشروع", "No tests in the project"],
    description: ["لم يُعثر على أي ملف اختبار ولم يُكتشف إطار اختبار.", "No test file was found and no test framework was detected."],
    impact: ["أي تعديل ينشر بلا شبكة أمان، والأخطاء تُكتشف في الإنتاج.", "Every change ships without a safety net and bugs surface in production."],
    recommendation: ["ابدأ باختبارات للوحدات الحرجة (مصادقة، دفع، وصول للبيانات).", "Start with tests for the critical paths: auth, payments and data access."],
    detection: ["أنماط أسماء ملفات الاختبار + إعدادات الحزم", "Test file name patterns plus package configuration"],
    references: [],
  }),
  def({
    id: "TST-002",
    engine: "tests",
    category: "tests",
    severity: "HIGH",
    confidence: 0.95,
    languages: "all",
    title: ["اختبارات فاشلة في النتائج المرفوعة", "Failing tests in the committed results"],
    description: ["ملف نتائج مرفوع مع المشروع يحتوي حالات فاشلة.", "A test result file committed with the project contains failing cases."],
    impact: ["المشروع ينشر بمعرفة مسبقة باختبارات فاشلة.", "The project ships with known failing tests."],
    recommendation: ["أصلح أو عطّل الاختبارات الفاشلة بشكل صريح مع تتبّع السبب.", "Fix the failing tests or explicitly skip them with a tracked reason."],
    detection: ["تحليل JUnit XML المرفوع", "Parsing committed JUnit XML"],
    references: [],
  }),
  def({
    id: "TST-003",
    engine: "tests",
    category: "tests",
    severity: "MEDIUM",
    confidence: 0.9,
    languages: "all",
    title: ["تغطية اختبارات منخفضة", "Low test coverage"],
    description: ["نسبة التغطية المعلنة في تقرير التغطية أقل من 50%.", "The coverage reported by the committed coverage report is below 50%."],
    impact: ["معظم الكود غير مُختبَر، والانحدارات تمر بصمت.", "Most code is untested and regressions pass silently."],
    recommendation: ["غطِّ المسارات الحرجة أولًا، ثم ارفع الحد تدريجيًا في CI.", "Cover critical paths first, then raise the threshold gradually in CI."],
    detection: ["قراءة lcov/coverage-summary.json", "Reading lcov/coverage-summary.json"],
    references: [],
  }),
  def({
    id: "TST-004",
    engine: "tests",
    category: "tests",
    severity: "LOW",
    confidence: 0.7,
    languages: "all",
    title: ["اختبارات موجودة بلا أمر تشغيل موثّق", "Tests exist without a documented run command"],
    description: ["ملفات اختبار موجودة لكن لا يوجد سكربت تشغيل واضح في ملفات الحزم.", "Test files exist but no clear run script in the package manifests."],
    impact: ["من الصعب على الفريق تشغيل نفس الاختبارات محليًا أو في CI.", "The team cannot easily run the same tests locally or in CI."],
    recommendation: ["أضف سكربت test موثّقًا واذكره في README.", "Add a documented test script and mention it in the README."],
    detection: ["وجود ملفات اختبار + سكربتات الحزم", "Presence of test files compared with package scripts"],
    references: [],
  }),
  def({
    id: "TST-005",
    engine: "tests",
    category: "tests",
    severity: "LOW",
    confidence: 0.8,
    languages: ["javascript", "typescript", "python", "php", "java", "dart"],
    title: ["اختبارات معطّلة (skip/only)", "Skipped or focused tests"],
    description: ["وجود .skip/.only أو @Ignore في ملفات الاختبار.", ".skip/.only or @Ignore appears in test files."],
    impact: ["اختبار مهم لا يعمل فعلًا، أو اختبار واحد فقط يُنفَّذ ويخفي غيره.", "An important test never runs, or only one test runs and hides the rest."],
    recommendation: ["أزل skip/only وأصلح الاختبار، أو وثّق سبب تعطيله.", "Remove skip/only and fix the test, or document why it is disabled."],
    detection: ["وسوم تعطيل الاختبارات", "Test-disabling markers"],
    references: [],
  }),
  def({
    id: "TST-006",
    engine: "tests",
    category: "tests",
    severity: "HIGH",
    confidence: 0.99,
    languages: ["javascript", "typescript"],
    title: ["اختبار فاشل عند التشغيل الفعلي", "Test fails when actually executed"],
    description: [
      "تم تشغيل الاختبار داخل صندوق تنفيذ محدود، وفشلت الحالة عند السطر المذكور في الأدلة.",
      "The test ran inside the restricted execution sandbox and the case failed at the line shown in the evidence.",
    ],
    impact: [
      "الفشل مؤكد بالتنفيذ لا بالتخمين: إما أن الكود مكسور أو أن الاختبار نفسه خاطئ، وكلاهما يجب أن يُحل قبل النشر.",
      "The failure is confirmed by execution rather than inferred: either the code is broken or the test is, and both must be resolved before shipping.",
    ],
    recommendation: [
      "أعد تشغيل الأمر نفسه محليًا، واقرأ رسالة الفشل، وأصلح الكود أو الاختبار ثم أعد التدقيق.",
      "Run the same command locally, read the failure message, fix the code or the test, then audit again.",
    ],
    detection: ["تشغيل ملفات node:test داخل عملية معزولة بصلاحيات مقيدة", "Running node:test files in a restricted child process"],
    references: [],
  }),
  def({
    id: "TST-007",
    engine: "tests",
    category: "tests",
    severity: "HIGH",
    confidence: 0.99,
    languages: ["javascript", "typescript"],
    title: ["ملف اختبار لا يُحمَّل أصلًا", "A test file does not even load"],
    description: [
      "عند التشغيل فشل تحميل الملف قبل تنفيذ أي حالة (خطأ صياغة أو استيراد مفقود)، فلم تُنفَّذ اختباراته.",
      "On execution the file failed to load before any case ran (syntax error or missing import), so none of its tests ran.",
    ],
    impact: [
      "المشروع يبدو مختبَرًا وهو ليس كذلك: كل اختبارات هذا الملف لا تعمل في أي بيئة.",
      "The project looks tested but is not: every test in this file is dead in every environment.",
    ],
    recommendation: ["أصلح خطأ التحميل ثم أعد التشغيل للتأكد من ظهور الحالات.", "Fix the load error, then run again and confirm the cases appear."],
    detection: ["تحليل مخرجات stderr لعملية التشغيل", "Reading the exit state and stderr of the executed process"],
    references: [],
  }),
  def({
    id: "TST-008",
    engine: "tests",
    category: "tests",
    severity: "MEDIUM",
    confidence: 0.99,
    languages: ["javascript", "typescript"],
    title: ["اختبارات لا تنتهي (تجاوزت المهلة)", "Tests never finish (deadline exceeded)"],
    description: [
      "الملف تجاوز مهلة التنفيذ المسموحة داخل الصندوق وقُتل، لذا لا نتيجة موثوقة له.",
      "The file exceeded its execution deadline inside the sandbox and was killed, so it has no trustworthy result.",
    ],
    impact: [
      "عادةً انتظار غير منتهٍ أو حلقة لا تنتهي أو وعد لا يُحل: وهذا يجعل CI معلّقًا أو الاختبارات معطّلة عمليًا.",
      "Usually an unbounded wait, an infinite loop or an unresolved promise: it hangs CI or effectively disables the suite.",
    ],
    recommendation: [
      "أضف مهلات صريحة داخل الاختبار، وتأكد من إغلاق الاتصالات والمؤقتات في نهاية كل حالة.",
      "Add explicit timeouts inside the test and make sure connections and timers are closed at the end of each case.",
    ],
    detection: ["إنهاء العملية بـ SIGKILL عند انتهاء المهلة", "Killing the child process with SIGKILL at the deadline"],
    references: [],
  }),
];
