import type { BilingualText, FindingCategory, EngineId, RuleDef, Severity } from "../types";
import { RULE_CATALOG_VERSION } from "../types";

type Pair = [string, string];

interface RuleInput {
  id: string;
  engine: EngineId;
  category: FindingCategory;
  severity: Severity;
  confidence: number;
  languages: string[] | "all";
  title: Pair;
  description: Pair;
  impact: Pair;
  recommendation: Pair;
  detection: Pair;
  references: string[];
}

function def(input: RuleInput): RuleDef {
  const bi = (pair: Pair): BilingualText => ({ ar: pair[0], en: pair[1] });
  return {
    id: input.id,
    engine: input.engine,
    category: input.category,
    severity: input.severity,
    confidence: input.confidence,
    languages: input.languages,
    name: bi(input.title),
    description: bi(input.description),
    impact: bi(input.impact),
    recommendation: bi(input.recommendation),
    detection: bi(input.detection),
    references: input.references,
    version: RULE_CATALOG_VERSION,
  };
}
const OWASP = "https://owasp.org/www-project-top-ten/";
const CWE = (id: number) => `https://cwe.mitre.org/data/definitions/${id}.html`;
const OSV = "https://osv.dev";

export const RULE_CATALOG: RuleDef[] = [
  /* ---------------------------- secrets ---------------------------- */
  def({
    id: "SEC-001",
    engine: "secrets",
    category: "secrets",
    severity: "HIGH",
    confidence: 0.92,
    languages: "all",
    title: ["مفتاح أو كلمة مرور مكتوبة داخل الكود", "Hardcoded credential in source"],
    description: [
      "تم العثور على قيمة تشبه مفتاح API أو كلمة مرور مكتوبة مباشرة في ملف مصدري.",
      "A value that looks like an API key or password is written directly into a source file.",
    ],
    impact: [
      "أي شخص لديه وصول للكود (أو لتاريخ Git) يمكنه استخدام المفتاح، وتغييره لاحقًا مكلف.",
      "Anyone with repository access — including its Git history — can use the key, and rotating it later is costly.",
    ],
    recommendation: [
      "انقل القيمة إلى متغير بيئة أو مدير أسرار، ثم أبطِل المفتاح المكشوف وأنشئ بديلًا.",
      "Move the value to an environment variable or secret manager, then revoke the exposed key and issue a new one.",
    ],
    detection: ["نمط نصّي + فحص سياق المتغير", "Pattern match plus variable-context check"],
    references: [CWE(798), OWASP],
  }),
  def({
    id: "SEC-002",
    engine: "secrets",
    category: "secrets",
    severity: "CRITICAL",
    confidence: 0.96,
    languages: "all",
    title: ["مفتاح خاص (Private Key) داخل المستودع", "Private key committed to the repository"],
    description: [
      "كتلة مفتاح خاص (RSA/EC/OpenSSH/PGP) موجودة في ملفات المشروع.",
      "A private key block (RSA/EC/OpenSSH/PGP) is present in the project files.",
    ],
    impact: [
      "تسريب مفتاح خاص يسمح بانتحال هوية الخدمة أو فك الاتصالات المشفّرة.",
      "A leaked private key allows impersonating the service or decrypting its traffic.",
    ],
    recommendation: [
      "احذف المفتاح من المستودع ومن تاريخ Git، وأنشئ مفتاحًا جديدًا، واستخدم مخزن أسرار.",
      "Remove the key from the repository and its Git history, generate a new key, and store it in a secret manager.",
    ],
    detection: ["تعرّف على رؤوس المفاتيح الخاصة", "Private-key header detection"],
    references: [CWE(321)],
  }),
  def({
    id: "SEC-003",
    engine: "secrets",
    category: "secrets",
    severity: "HIGH",
    confidence: 0.85,
    languages: "all",
    title: ["توكن وصول مكتوب في الكود", "Access token literal in code"],
    description: [
      "توكن مصادقة (Bearer/JWT/سلسلة طويلة عالية العشوائية) موضوع في ملف مصدري.",
      "An authentication token (Bearer/JWT/high-entropy string) is embedded in a source file.",
    ],
    impact: ["التوكن يمنح وصولًا للنظام باسم المالك حتى انتهاء صلاحيته.", "The token grants access on the owner's behalf until it expires."],
    recommendation: [
      "استخدم متغيرات بيئة وجلسات قصيرة العمر، وأبطِل التوكن الحالي.",
      "Use environment variables and short-lived sessions, and revoke the current token.",
    ],
    detection: ["أنماط توكنات (JWT, Bearer, بادئات مزوّدين) + Entropy", "Token patterns (JWT, Bearer, provider prefixes) plus entropy"],
    references: [CWE(522)],
  }),
  def({
    id: "SEC-004",
    engine: "secrets",
    category: "secrets",
    severity: "HIGH",
    confidence: 0.8,
    languages: "all",
    title: ["ملف أسرار مُلتزَم في المستودع", "A secrets file is committed"],
    description: [
      "ملف بيئة أو مفتاح (‎.env, .env.local, secrets.yml …) مرفوع مع المشروع ويحمل قيمًا حقيقية.",
      "An environment or key file (.env, .env.local, secrets.yml …) ships with the project and holds real values.",
    ],
    impact: ["كل من يقرأ المستودع يحصل على أسرار البيئة كاملة.", "Everyone who can read the repository gets the complete environment secrets."],
    recommendation: [
      "احتفظ بملف مثال فقط (.env.example) وامنع الملف الحقيقي في .gitignore.",
      "Keep only an example file (.env.example) and ignore the real one in .gitignore.",
    ],
    detection: ["أسماء الملفات + وجود قيم غير نموذجية", "File-name check plus presence of non-placeholder values"],
    references: [CWE(538)],
  }),
  def({
    id: "SEC-005",
    engine: "secrets",
    category: "secrets",
    severity: "MEDIUM",
    confidence: 0.6,
    languages: "all",
    title: ["نص عالي العشوائية يُسند إلى متغير سري", "High-entropy literal assigned to a secret-looking variable"],
    description: [
      "متغير اسمه يشير إلى سر (secret/key/password) يحمل نصًا طويلًا عشوائيًا ثابتًا.",
      "A variable named like a secret (secret/key/password) holds a long, fixed, random-looking string.",
    ],
    impact: ["قد يكون مفتاحًا حقيقيًا لم يُلاحظ؛ وقد يكون قيمة اختبار — يحتاج تأكيدًا بشريًا.", "May be a real key that went unnoticed, or a test value — needs human confirmation."],
    recommendation: ["انقله إلى متغير بيئة أو أضف تعليقًا صريحًا إن كان قيمة اختبار.", "Move it to an environment variable, or mark it explicitly if it is a test value."],
    detection: ["Entropy + اسم المتغير", "Entropy plus variable naming"],
    references: [CWE(798)],
  }),
  def({
    id: "SEC-006",
    engine: "secrets",
    category: "secrets",
    severity: "HIGH",
    confidence: 0.9,
    languages: "all",
    title: ["رابط قاعدة بيانات يحمل كلمة مرور", "Database URL carrying credentials"],
    description: [
      "سلسلة اتصال تحتوي على اسم مستخدم وكلمة مرور ظاهرة داخل الكود.",
      "A connection string containing a visible username and password appears in code.",
    ],
    impact: ["وصول مباشر لقاعدة البيانات من أي شخص يرى الملف.", "Direct database access for anyone who sees the file."],
    recommendation: ["اقرأ السلسلة من متغير بيئة، وقيّد صلاحيات المستخدم، وغيّر كلمة المرور.", "Read the string from an environment variable, restrict the account, and rotate the password."],
    detection: ["نمط بروتوكولات قواعد البيانات مع بيانات اعتماد", "Database protocol patterns with inline credentials"],
    references: [CWE(798)],
  }),
  def({
    id: "SEC-007",
    engine: "secrets",
    category: "secrets",
    severity: "HIGH",
    confidence: 0.88,
    languages: "all",
    title: ["بيانات اعتماد داخل رابط", "Credentials embedded in a URL"],
    description: [
      "رابط بصيغة https://user:password@host ينشر كلمة المرور كنص صريح.",
      "A URL of the form https://user:password@host exposes the password in clear text.",
    ],
    impact: ["كلمة المرور تظهر في السجلات وأدوات المراقبة ورسائل الأخطاء.", "The password leaks into logs, monitoring tools and error messages."],
    recommendation: ["أزل بيانات الاعتماد من الرابط واستخدم ترويسة مصادقة أو مدير أسرار.", "Remove credentials from the URL and use an auth header or secret manager."],
    detection: ["نمط URL مع عنصر مصادقة", "URL pattern with a userinfo component"],
    references: [CWE(522)],
  }),

  /* ---------------------------- security --------------------------- */
  def({
    id: "SEC-101",
    engine: "security",
    category: "security",
    severity: "HIGH",
    confidence: 0.85,
    languages: ["javascript", "typescript", "php", "python"],
    title: ["استخدام eval أو كود ديناميكي", "Use of eval or dynamic code execution"],
    description: [
      "تنفيذ نص ككود (eval / new Function / exec) ويمكن أن يصل إليه مدخل مستخدم.",
      "A string is executed as code (eval / new Function / exec) and user input can reach it.",
    ],
    impact: ["تنفيذ أوامر عشوائية داخل الخادم باسم التطبيق.", "Arbitrary code execution on the server as the application."],
    recommendation: ["استبدل eval بتحليل صريح أو مكتبة تحليل، وتحقق من أي مدخل يُمرَّر.", "Replace eval with explicit parsing or a parser library, and validate anything passed to it."],
    detection: ["نداءات AST/نصّية لـ eval/new Function/exec", "AST and textual calls to eval/new Function/exec"],
    references: [CWE(95), OWASP],
  }),
  def({
    id: "SEC-102",
    engine: "security",
    category: "security",
    severity: "HIGH",
    confidence: 0.8,
    languages: ["javascript", "typescript", "python", "php", "ruby", "go"],
    title: ["احتمال حقن أوامر (Command Injection)", "Possible command injection"],
    description: [
      "تنفيذ أمر نظام مع بناء النص من متغير — قد يحتوي على مدخل غير موثوق.",
      "A system command is built from a variable that may contain untrusted input.",
    ],
    impact: ["تنفيذ أوامر على الخادم: قراءة ملفات، حذف بيانات، أو pivot للشبكة الداخلية.", "Command execution on the host: file reads, data loss, or a pivot into the internal network."],
    recommendation: ["استخدم واجهات بلا shell ومرّر الوسائط كمصفوفة، وتحقق من المدخل بقائمة بيضاء.", "Use shell-free APIs with an argument array, and validate input against an allow-list."],
    detection: ["دوال shell + تسلسل نصي مع متغير", "Shell functions plus string concatenation with a variable"],
    references: [CWE(78)],
  }),
  def({
    id: "SEC-103",
    engine: "security",
    category: "security",
    severity: "HIGH",
    confidence: 0.78,
    languages: ["javascript", "typescript", "python", "php", "ruby", "java", "csharp"],
    title: ["بناء استعلام SQL بنص متغيّر", "SQL query built from a variable"],
    description: [
      "استعلام SQL يُبنى بدمج النص مع متغير بدل استخدام معاملات مربوطة.",
      "A SQL query concatenates or interpolates a variable instead of using bound parameters.",
    ],
    impact: ["حقن SQL: قراءة أو تعديل بيانات لا يملك المستخدم صلاحيتها.", "SQL injection: reading or modifying data the user is not authorised to touch."],
    recommendation: ["استخدم استعلامات مُعامَلة (prepared statements) ولا تدمج المدخل أبدًا.", "Use prepared statements with bound parameters; never interpolate input."],
    detection: ["بناء استعلام + متغير أو Template Literal", "Query construction plus a variable or template literal"],
    references: [CWE(89), OWASP],
  }),
  def({
    id: "SEC-104",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.75,
    languages: ["javascript", "typescript", "php", "ruby"],
    title: ["إدراج HTML خام (خطر XSS)", "Raw HTML injection (XSS risk)"],
    description: [
      "يُدرج HTML خام في الواجهة عبر dangerouslySetInnerHTML أو innerHTML أو v-html.",
      "Raw HTML is injected into the UI via dangerouslySetInnerHTML, innerHTML or v-html.",
    ],
    impact: ["تنفيذ سكربت في متصفح المستخدم وسرقة جلسته.", "Script execution in a user's browser and session theft."],
    recommendation: ["أعِد النص كقيمة نصية، أو نظّفه بمكتبة تنقية قبل الإدراج.", "Render the value as text, or sanitise it with a well-known library first."],
    detection: ["نداءات إدراج HTML خام", "Raw-HTML injection call sites"],
    references: [CWE(79)],
  }),
  def({
    id: "SEC-105",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.65,
    languages: ["javascript", "typescript", "python", "php", "go", "java"],
    title: ["احتمال تجاوز المسار (Path Traversal)", "Possible path traversal"],
    description: [
      "يُبنى مسار ملف من مدخل قد يحتوي على ../ أو مسار مطلق.",
      "A file path is built from input that may contain ../ or an absolute path.",
    ],
    impact: ["قراءة أو كتابة ملفات خارج مجلد التطبيق.", "Reading or writing files outside the application directory."],
    recommendation: ["طبّع المسار وتأكد أنه داخل المجلد المسموح، وارفض المسارات المطلقة.", "Normalise the path, verify it stays inside the allowed directory, and reject absolute paths."],
    detection: ["دوال قراءة/كتابة ملفات + دمج متغير", "File read/write functions combined with a variable"],
    references: [CWE(22)],
  }),
  def({
    id: "SEC-106",
    engine: "security",
    category: "security",
    severity: "HIGH",
    confidence: 0.85,
    languages: ["python", "php", "ruby", "java"],
    title: ["فك تسلسل غير آمن للبيانات", "Unsafe deserialisation"],
    description: [
      "فك تسلسل بيانات غير موثوقة (pickle, unserialize, yaml.load بلا SafeLoader).",
      "Untrusted data is deserialised (pickle, unserialize, yaml.load without SafeLoader).",
    ],
    impact: ["تنفيذ كود عند فك التسلسل، وهو مسار هجوم معروف.", "Code execution during deserialisation, a well-known attack path."],
    recommendation: ["استخدم صيغًا آمنة (JSON) أو الأوضاع الآمنة (yaml.safe_load) وارفض المدخل الخارجي.", "Use safe formats (JSON) or safe modes (yaml.safe_load) and refuse external input."],
    detection: ["دوال فك تسلسل معروفة", "Known deserialisation entry points"],
    references: [CWE(502)],
  }),
  def({
    id: "SEC-107",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.8,
    languages: ["javascript", "typescript", "python", "php", "java", "csharp"],
    title: ["دالة تشفير ضعيفة لكلمة المرور", "Weak hashing used for passwords"],
    description: ["استخدام MD5/SHA1 لتجزئة كلمات المرور.", "MD5/SHA1 is used to hash passwords."],
    impact: ["كسر كلمات المرور بسرعة بقوائم جاهزة عند تسريب القاعدة.", "Passwords are cracked quickly from a leaked database."],
    recommendation: ["استخدم bcrypt/argon2/scrypt مع ملح عشوائي لكل مستخدم.", "Use bcrypt/argon2/scrypt with a per-user random salt."],
    detection: ["دوال تجزئة قديمة في سياق كلمات المرور", "Legacy hash functions in a password context"],
    references: [CWE(916)],
  }),
  def({
    id: "SEC-108",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.7,
    languages: ["javascript", "typescript", "python", "php", "java", "go"],
    title: ["مولّد أرقام غير آمن للتوكنات", "Non-cryptographic randomness for tokens"],
    description: ["استخدام Math.random/random.random لتوليد توكن أو كود تحقق.", "Math.random/random.random generates a token or verification code."],
    impact: ["إمكانية توقّع التوكن وتجاوز المصادقة.", "Tokens become predictable, allowing authentication bypass."],
    recommendation: ["استخدم crypto.randomUUID / secrets / SecureRandom.", "Use crypto.randomUUID / secrets / SecureRandom."],
    detection: ["مولّد عشوائي ضعيف في سياق أمني", "Weak RNG in a security context"],
    references: [CWE(338)],
  }),
  def({
    id: "SEC-109",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.6,
    languages: ["javascript", "typescript", "php", "python"],
    title: ["رفع ملفات بلا قيود واضحة", "File upload without clear restrictions"],
    description: [
      "معالج رفع ملفات لا يفحص النوع أو الحجم قبل التخزين.",
      "An upload handler stores files without checking type or size first.",
    ],
    impact: ["رفع ملفات تنفيذية أو ملفات ضخمة تستهلك التخزين.", "Executable files or oversized uploads can be stored."],
    recommendation: ["حدّد الأنواع المسموحة بالمحتوى لا بالاسم، وحدّد حجمًا أقصى، وامنع التنفيذ في مجلد التخزين.", "Validate allowed types by content, cap the size, and prevent execution in the storage folder."],
    detection: ["دوال رفع ملفات + غياب فحص النوع/الحجم", "Upload handlers without type or size checks"],
    references: [CWE(434)],
  }),
  def({
    id: "SEC-110",
    engine: "security",
    category: "security",
    severity: "HIGH",
    confidence: 0.85,
    languages: ["javascript", "typescript", "php", "python", "java"],
    title: ["CORS مفتوح للجميع مع بيانات الاعتماد", "Wildcard CORS with credentials"],
    description: ["إعداد CORS يسمح لأي أصل مع credentials: true.", "CORS is configured for any origin together with credentials: true."],
    impact: ["مواقع أخرى تقرأ بيانات المستخدم المُصادَق عليه.", "Other sites can read the authenticated user's data."],
    recommendation: ["استخدم قائمة أصول صريحة، وتجنّب الجمع بين * وcredentials.", "Use an explicit allow-list and never combine * with credentials."],
    detection: ["إعدادات CORS مع '*'", "CORS configuration containing '*'"],
    references: [CWE(942)],
  }),
  def({
    id: "SEC-111",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.75,
    languages: "all",
    title: ["وضع التصحيح مفعّل في إعدادات الإنتاج", "Debug mode enabled in production settings"],
    description: ["‏APP_DEBUG/DEBUG=true أو DEVELOPMENT=1 في إعدادات المشروع.", "APP_DEBUG/DEBUG=true or DEVELOPMENT=1 in the project configuration."],
    impact: ["كشف تفاصيل داخلية ومسارات وأسرار للمستخدمين.", "Internal details, paths and secrets leak to users."],
    recommendation: ["أوقف التصحيح في الإنتاج وفعّله بمتغير بيئة للتطوير فقط.", "Disable debug in production and enable it through a development-only variable."],
    detection: ["قيم إعدادات معروفة للتصحيح", "Well-known debug configuration values"],
    references: [CWE(489)],
  }),
  def({
    id: "SEC-112",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.7,
    languages: "all",
    title: ["تسجيل بيانات حساسة", "Sensitive data written to logs"],
    description: ["سجلّ يطبع كلمة مرور أو توكن أو بيانات بطاقة.", "A log statement prints a password, token or card data."],
    impact: ["الأسرار تُحفظ في السجلات وتظهر لكل من يقرأها.", "Secrets persist in logs and are readable by anyone with log access."],
    recommendation: ["أخفِ الحقول الحساسة قبل التسجيل أو امتنع عن تسجيل الكائن كاملًا.", "Mask sensitive fields before logging, or stop logging the whole object."],
    detection: ["دوال تسجيل مع حقول حساسة", "Logging calls with sensitive field names"],
    references: [CWE(532)],
  }),
  def({
    id: "SEC-113",
    engine: "security",
    category: "security",
    severity: "HIGH",
    confidence: 0.85,
    languages: ["javascript", "typescript", "python", "php", "go", "java"],
    title: ["إيقاف التحقق من شهادة TLS", "TLS certificate verification disabled"],
    description: ["إعداد يتجاهل التحقق من الشهادة (rejectUnauthorized:false, verify=False).", "A setting ignores certificate validation (rejectUnauthorized:false, verify=False)."],
    impact: ["هجوم رجل-في-الوسط يصبح ممكنًا على كل الاتصالات.", "Man-in-the-middle attacks become possible on every request."],
    recommendation: ["أزل الإعداد وأصلح شهادة الخادم أو أضف CA الموثوق.", "Remove the flag and fix the server certificate or trust the correct CA."],
    detection: ["خيارات عميل HTTP معروفة", "Known HTTP client options"],
    references: [CWE(295)],
  }),
  def({
    id: "SEC-114",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.65,
    languages: ["javascript", "typescript", "php", "python"],
    title: ["إعادة توجيه إلى عنوان من المدخل", "Redirect to a user-controlled target"],
    description: ["إعادة توجيه أو جلب رابط من مدخل المستخدم بلا قائمة تحقق.", "A redirect or fetch target comes from user input without validation."],
    impact: ["تصيّد عبر نطاقك، أو وصول لخدمات داخلية (SSRF).", "Phishing through your domain, or access to internal services (SSRF)."],
    recommendation: ["اسمح بقائمة مسارات داخلية فقط، وامنع العناوين الداخلية.", "Allow only a list of internal paths and block internal addresses."],
    detection: ["دوال إعادة التوجيه مع مدخل", "Redirect helpers combined with request input"],
    references: [CWE(601), CWE(918)],
  }),
  def({
    id: "SEC-115",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.7,
    languages: ["javascript", "typescript"],
    title: ["تخزين أسرار المتصفح في localStorage", "Browser secrets kept in localStorage"],
    description: ["توكن مصادقة يُخزَّن في localStorage بدل كوكي آمن.", "An auth token is stored in localStorage instead of a secure cookie."],
    impact: ["أي ثغرة XSS تسرق التوكن بسهولة.", "Any XSS immediately steals the token."],
    recommendation: ["استخدم كوكي httpOnly وSameSite مع جلسة على الخادم.", "Use an httpOnly, SameSite cookie backed by a server session."],
    detection: ["استدعاءات التخزين المحلي مع أسماء توكنات", "Local-storage calls with token-like keys"],
    references: [CWE(922)],
  }),
  def({
    id: "SEC-116",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.6,
    languages: ["python"],
    title: ["تنفيذ أمر shell=True", "subprocess executed with shell=True"],
    description: ["تشغيل عملية عبر shell مع نص مبني من متغير.", "A process runs through a shell with a string built from a variable."],
    impact: ["حقن أوامر عند تلويث أي جزء من النص.", "Command injection if any part of the string is tainted."],
    recommendation: ["استخدم قائمة وسائط مع shell=False.", "Pass an argument list with shell=False."],
    detection: ["وسائط subprocess/os.system", "subprocess/os.system arguments"],
    references: [CWE(78)],
  }),
  def({
    id: "SEC-117",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.7,
    languages: ["php"],
    title: ["حماية CSRF معطّلة", "CSRF protection disabled"],
    description: ["تعطيل حماية CSRF في إطار العمل (csrf_exempt أو ما يعادله).", "The framework's CSRF protection is disabled (csrf_exempt or similar)."],
    impact: ["طلب مزيّف من موقع آخر ينفّذ عملية باسم المستخدم.", "A forged request from another site performs an action as the user."],
    recommendation: ["أعد تفعيل الحماية أو وفّر تحققًا بديلًا للتوكن.", "Re-enable protection or provide equivalent token validation."],
    detection: ["وسوم تعطيل الحماية", "Disablement annotations"],
    references: [CWE(352)],
  }),
  def({
    id: "SEC-118",
    engine: "security",
    category: "security",
    severity: "MEDIUM",
    confidence: 0.65,
    languages: ["php"],
    title: ["إسناد جماعي غير محمي", "Unprotected mass assignment"],
    description: ["نموذج مفتوح للتعديل الجماعي (‎$guarded = [] أو fillable واسع).", "A model is open to mass assignment ($guarded = [] or a very wide fillable list)."],
    impact: ["مستخدم يستطيع تعديل حقول حساسة مثل role أو is_admin.", "A user can modify sensitive fields such as role or is_admin."],
    recommendation: ["استخدم قائمة fillable صريحة واستبعد الحقول الحساسة.", "Use an explicit fillable list and exclude sensitive fields."],
    detection: ["خصائص النماذج في إطار العمل", "Framework model properties"],
    references: [CWE(915)],
  }),
  def({
    id: "SEC-119",
    engine: "security",
    category: "security",
    severity: "LOW",
    confidence: 0.6,
    languages: "all",
    title: ["تعليق يحتوي على كود معطّل", "Commented-out code left behind"],
    description: ["كود قديم معلَّق بجانب كود فعّال.", "Old code is commented out next to live code."],
    impact: ["صعوبة معرفة السلوك الصحيح، وقد يُحيي كودًا غير آمن لاحقًا.", "It becomes hard to know the real behaviour, and unsafe code may be revived later."],
    recommendation: ["احذفه — تاريخ Git يحفظه إن احتجته.", "Delete it — Git history keeps it if you need it."],
    detection: ["تعليقات تشبه كودًا في سياق دالة", "Code-like comments inside a function body"],
    references: [],
  }),

  /* -------------------------- dependencies ------------------------- */
  def({
    id: "DEP-001",
    engine: "dependencies",
    category: "dependencies",
    severity: "HIGH",
    confidence: 0.95,
    languages: "all",
    title: ["تبعية مصابة بثغرة معروفة", "Dependency with a known vulnerability"],
    description: ["حزمة مستخدمة في المشروع لها تحذير أمني منشور.", "A package used by the project has a published security advisory."],
    impact: ["الثغرة قابلة للاستغلال من خارج النظام مباشرة.", "The vulnerability is directly reachable from outside the system."],
    recommendation: ["حدّث الحزمة إلى الإصدار المُصلِح المذكور في التحذير.", "Upgrade the package to the fixed version listed in the advisory."],
    detection: ["مطابقة الإصدارات مع قاعدة OSV", "Version matching against the OSV database"],
    references: [OSV],
  }),
  def({
    id: "DEP-002",
    engine: "dependencies",
    category: "dependencies",
    severity: "LOW",
    confidence: 0.85,
    languages: "all",
    title: ["إصدار تبعية غير مثبَّت", "Dependency version is not pinned"],
    description: ["الحزمة مطلوبة بنطاق مفتوح أو latest بدل إصدار محدد.", "The package is requested with an open range or latest instead of a fixed version."],
    impact: ["تحديث غير متوقع قد يكسر المشروع أو يُدخل كودًا غير مراجَع.", "An unexpected update can break the build or pull in unreviewed code."],
    recommendation: ["ثبّت الإصدار (exact) أو استخدم lock file وأبقِه في المستودع.", "Pin the exact version, or keep a lock file committed in the repository."],
    detection: ["قراءة بادئات النطاقات في ملفات الحزم", "Range prefixes in package manifests"],
    references: [],
  }),
  def({
    id: "DEP-003",
    engine: "dependencies",
    category: "dependencies",
    severity: "LOW",
    confidence: 0.75,
    languages: "all",
    title: ["حزمة متأخرة عن أحدث إصدار رئيسي", "Package far behind the latest release"],
    description: ["النسخة المثبّتة أقدم بكثير من أحدث إصدار منشور.", "The pinned version is well behind the latest published release."],
    impact: ["إصلاحات الأمان والتحسينات غير موجودة في مشروعك.", "Security fixes and improvements are missing from your project."],
    recommendation: ["خطّط ترقية تدريجية مع اختبارات قبل الدمج.", "Plan a staged upgrade with tests before merging."],
    detection: ["مقارنة الإصدار بأحدث إصدار من السجل العام", "Version compared with the latest published release"],
    references: [],
  }),
  def({
    id: "DEP-004",
    engine: "dependencies",
    category: "dependencies",
    severity: "INFO",
    confidence: 1,
    languages: "all",
    title: ["تعذّر التحقق من التبعيات", "Dependency verification unavailable"],
    description: ["لم يتم الاتصال بقاعدة التحذيرات، فلم تُفحص هذه التبعيات (لا يعني أنها سليمة).", "The advisory database could not be reached, so these dependencies were not checked (this does not mean they are clean)."],
    impact: ["غياب نتيجة ليس دليلًا على السلامة.", "A missing result is not proof of safety."],
    recommendation: ["أعد التدقيق لاحقًا أو استخدم أداة فحص محليًا.", "Re-run the audit later or scan locally with your own tool."],
    detection: ["تسجيل حالة الاتصال بمصدر التحذيرات", "Recorded status of the advisory source"],
    references: [OSV],
  }),

  /* ---------------------------- quality ---------------------------- */
  def({
    id: "QUA-001",
    engine: "quality",
    category: "quality",
    severity: "LOW",
    confidence: 0.95,
    languages: ["javascript", "typescript", "python", "php", "java", "csharp", "go", "ruby"],
    title: ["دالة طويلة جدًا", "Function is very long"],
    description: ["طول الدالة يتجاوز الحد المتفق عليه (60 سطرًا).", "The function body exceeds the agreed limit (60 lines)."],
    impact: ["صعوبة المراجعة والاختبار وزيادة احتمال الأخطاء.", "Harder to review and test, and more likely to hide defects."],
    recommendation: ["قسّم الدالة إلى خطوات صغيرة بأسماء واضحة.", "Split the function into small, well-named steps."],
    detection: ["قياس أسطر جسم الدالة", "Measuring function body lines"],
    references: [],
  }),
  def({
    id: "QUA-002",
    engine: "quality",
    category: "quality",
    severity: "MEDIUM",
    confidence: 0.9,
    languages: ["javascript", "typescript", "python", "php", "java", "csharp", "go", "ruby"],
    title: ["تعقيد دوري مرتفع", "High cyclomatic complexity"],
    description: ["عدد مسارات التنفيذ في الدالة كبير (أكثر من 15).", "The number of execution paths in the function is high (over 15)."],
    impact: ["عدد الحالات التي يجب اختبارها كبير، والمنطق صعب التتبع.", "Many cases need testing and the logic is hard to follow."],
    recommendation: ["استخرج الشروط المتكررة إلى دوال، واستبدل الفروع المتشابكة بجدول قرار.", "Extract repeated conditions into functions and replace nested branches with a decision table."],
    detection: ["عدّ الفروع والحلقات في الـAST", "Counting branches and loops in the AST"],
    references: [],
  }),
  def({
    id: "QUA-003",
    engine: "quality",
    category: "quality",
    severity: "LOW",
    confidence: 0.8,
    languages: "all",
    title: ["كتلة كود مكررة", "Duplicated code block"],
    description: ["كتلة من الأسطر المتطابقة (بعد التطبيع) تتكرر في أكثر من موضع.", "A block of identical lines (after normalisation) appears in more than one place."],
    impact: ["إصلاح الخلل في نسخة واحدة يترك الأخرى مكسورة.", "Fixing a bug in one copy leaves the other broken."],
    recommendation: ["استخرج الكتلة المشتركة إلى دالة أو وحدة مشتركة.", "Extract the shared block into one function or module."],
    detection: ["تجزئة نوافذ أسطر مُطبَّعة ومقارنتها", "Hashing normalised line windows and comparing them"],
    references: [],
  }),
  def({
    id: "QUA-004",
    engine: "quality",
    category: "quality",
    severity: "MEDIUM",
    confidence: 0.85,
    languages: ["javascript", "typescript", "python", "php", "java", "csharp", "dart"],
    title: ["خطأ مُبتلَع بدون معالجة", "Error swallowed without handling"],
    description: ["كتلة catch فارغة أو تتجاهل الخطأ بلا تسجيل ولا معالجة.", "An empty catch block ignores the error without logging or handling."],
    impact: ["تفشل العمليات بصمت ويستحيل تشخيص المشكلة في الإنتاج.", "Operations fail silently and production issues become undiagnosable."],
    recommendation: ["سجّل الخطأ مع سياقه، أو أعد رميه بعد تغليفه برسالة واضحة.", "Log the error with context, or rethrow it wrapped with a clear message."],
    detection: ["كتل catch بلا تعليمات", "Catch blocks with an empty body"],
    references: [],
  }),
  def({
    id: "QUA-005",
    engine: "quality",
    category: "quality",
    severity: "LOW",
    confidence: 0.9,
    languages: "all",
    title: ["ملف كبير جدًا", "Oversized source file"],
    description: ["الملف يتجاوز 600 سطر منطقي.", "The file exceeds 600 logical lines."],
    impact: ["الملف يجمع مسؤوليات كثيرة ويصعب مراجعته.", "The file mixes many responsibilities and is hard to review."],
    recommendation: ["افصل الأنواع والدوال ذات المسؤولية الواحدة إلى ملفات.", "Split types and functions into files with a single responsibility."],
    detection: ["عدّ الأسطر المنطقية لكل ملف", "Counting logical lines per file"],
    references: [],
  }),
  def({
    id: "QUA-006",
    engine: "quality",
    category: "quality",
    severity: "LOW",
    confidence: 0.85,
    languages: ["javascript", "typescript", "python", "php", "java", "csharp", "go", "dart"],
    title: ["عدد وسائط كبير", "Function takes too many parameters"],
    description: ["الدالة تستقبل أكثر من 6 وسائط.", "The function accepts more than 6 parameters."],
    impact: ["احتمال تبديل الوسائط عند الاستدعاء وارد جدًا.", "Arguments are easily passed in the wrong order."],
    recommendation: ["اجمع الوسائط في كائن/بنية واضحة.", "Group the parameters into a single options object or struct."],
    detection: ["عدّ وسائط تعريف الدالة", "Counting declared function parameters"],
    references: [],
  }),
  def({
    id: "QUA-007",
    engine: "quality",
    category: "quality",
    severity: "LOW",
    confidence: 0.8,
    languages: ["javascript", "typescript", "python", "php", "java", "csharp", "dart"],
    title: ["تداخل شروط عميق", "Deeply nested conditions"],
    description: ["مستوى التداخل داخل الدالة يتجاوز 5 مستويات.", "Nesting inside the function goes deeper than 5 levels."],
    impact: ["صعوبة تتبع المسار المنطقي وارتفاع احتمال الخطأ.", "The control flow is hard to follow and error-prone."],
    recommendation: ["استخدم الحماية المبكرة (early return) وأخرج الشروط إلى دوال.", "Use early returns and extract conditions into named functions."],
    detection: ["قياس أقصى عمق للكتل في الـAST", "Measuring maximum block depth in the AST"],
    references: [],
  }),
  def({
    id: "QUA-008",
    engine: "quality",
    category: "quality",
    severity: "INFO",
    confidence: 0.95,
    languages: "all",
    title: ["تعليق مؤجَّل (TODO/FIXME/HACK)", "Unfinished-work comment (TODO/FIXME/HACK)"],
    description: ["تعليق يسجّل عملًا مؤجلًا أو حلًا مؤقتًا.", "A comment records deferred work or a temporary workaround."],
    impact: ["دَين تقني غير متتبع، وأحيانًا مشكلة أمنية معروفة مؤجّلة.", "Untracked technical debt — sometimes a known security issue postponed."],
    recommendation: ["حوّل التعليق إلى مهمة متتبَّعة، أو أزل التعليق بعد الحل.", "Turn the comment into a tracked task, or remove it once resolved."],
    detection: ["وسوم تعليقات معروفة", "Well-known comment markers"],
    references: [],
  }),
  def({
    id: "QUA-009",
    engine: "quality",
    category: "quality",
    severity: "INFO",
    confidence: 0.9,
    languages: ["javascript", "typescript", "php", "dart"],
    title: ["طباعة تشخيصية في كود الإنتاج", "Diagnostic logging left in production code"],
    description: ["نداء console.log/debug في كود غير اختباري.", "A console.log/debug call sits in non-test code."],
    impact: ["تلويث السجلات وإمكانية تسريب بيانات.", "Noisy logs and possible data leakage."],
    recommendation: ["استخدم مكتبة تسجيل بمستويات، واحذف الطبعات المؤقتة.", "Use a levelled logger and remove temporary prints."],
    detection: ["عدّ نداءات الطباعة لكل ملف", "Counting print calls per file"],
    references: [],
  }),
  def({
    id: "QUA-010",
    engine: "quality",
    category: "quality",
    severity: "LOW",
    confidence: 0.9,
    languages: ["typescript"],
    title: ["إسكات فحص الأنواع", "Type checking silenced"],
    description: ["استخدام ts-ignore/ts-expect-error/any واسع لتعطيل فحص الأنواع.", "ts-ignore/ts-expect-error or a broad any disables type checking."],
    impact: ["الأخطاء التي كان سيكشفها المترجم تصل إلى الإنتاج.", "Errors the compiler would have caught reach production."],
    recommendation: ["استبدل الإسكات بنوع صريح أو تحقق يدوي من المدخل.", "Replace the suppression with an explicit type or a runtime check."],
    detection: ["وسوم الإسكات واستخدامات any", "Suppression comments and any usages"],
    references: [],
  }),

  /* -------------------------- architecture ------------------------- */
  def({
    id: "ARC-001",
    engine: "architecture",
    category: "architecture",
    severity: "MEDIUM",
    confidence: 0.9,
    languages: "all",
    title: ["اعتمادية دائرية بين الوحدات", "Circular dependency between modules"],
    description: ["وحدة تستورد وحدة تستورد الأولى، مباشرة أو عبر سلسلة.", "A module imports another that imports it back, directly or through a chain."],
    impact: ["ترتيب التحميل غير متوقع، وصعوبة اختبار الوحدات منفصلة.", "Load order becomes unpredictable and modules cannot be tested in isolation."],
    recommendation: ["افصل الجزء المشترك في وحدة ثالثة، أو اعكس الاعتماد بواجهة.", "Extract the shared part into a third module, or invert the dependency behind an interface."],
    detection: ["رسم اعتماديات الاستيراد ثم كشف الحلقات", "Import graph construction followed by cycle detection"],
    references: [],
  }),
  def({
    id: "ARC-002",
    engine: "architecture",
    category: "architecture",
    severity: "LOW",
    confidence: 0.75,
    languages: "all",
    title: ["وحدة عالية الارتباط", "Highly coupled module"],
    description: ["وحدة تستورد عددًا كبيرًا من الوحدات أو يعتمد عليها عدد كبير.", "A module imports many others, or many others depend on it."],
    impact: ["أي تغيير صغير ينتشر في المشروع كله.", "A small change ripples across the whole project."],
    recommendation: ["قسّم الوحدة على مسؤوليات أو أدخل واجهة وسيطة.", "Split the module by responsibility or introduce a mediating interface."],
    detection: ["حساب fan-in/fan-out ومؤشر عدم الاستقرار", "Computing fan-in/fan-out and an instability index"],
    references: [],
  }),
  def({
    id: "ARC-003",
    engine: "architecture",
    category: "architecture",
    severity: "MEDIUM",
    confidence: 0.65,
    languages: ["javascript", "typescript"],
    title: ["واجهة الواجهة الأمامية تستورد طبقة البيانات", "Front-end code imports the data layer directly"],
    description: ["ملف واجهة (component/page) يستورد مشغّل قاعدة بيانات أو استعلامًا مباشرًا.", "A UI file (component/page) imports a database driver or a direct query."],
    impact: ["منطق البيانات يتسرب للواجهة، ويصبح من الصعب تأمين الصلاحيات وتغيير الطبقة.", "Data logic leaks into the UI, and authorisation plus refactoring become harder."],
    recommendation: ["اجعل الواجهة تنادي API فقط، واترك الوصول للبيانات في الخادم.", "Have the UI call an API only, and keep data access on the server."],
    detection: ["مسار الملف + حزمة مستوردة معروفة لقواعد البيانات", "File path plus a known database import"],
    references: [],
  }),
  def({
    id: "ARC-004",
    engine: "architecture",
    category: "architecture",
    severity: "LOW",
    confidence: 0.85,
    languages: "all",
    title: ["وحدة ضخمة تجمع مسؤوليات", "Oversized module"],
    description: ["وحدة تتجاوز 800 سطر منطقي.", "A module exceeds 800 logical lines."],
    impact: ["الوحدة تصبح نقطة تغيير دائمة وسببًا للتعارضات.", "The module becomes a permanent change hotspot and a merge-conflict source."],
    recommendation: ["فكّك الوحدة حسب حالات الاستخدام، وابدأ بأكثر الأجزاء تغيّرًا.", "Break the module down by use case, starting with the parts that change most."],
    detection: ["حساب الأسطر المنطقية لكل وحدة", "Logical line count per module"],
    references: [],
  }),

  /* ------------------------------- api ----------------------------- */
  def({
    id: "API-001",
    engine: "api",
    category: "api",
    severity: "HIGH",
    confidence: 0.6,
    languages: ["javascript", "typescript", "php", "python", "ruby", "java", "csharp", "go"],
    title: ["مسار يغيّر البيانات بلا إشارة تصريح", "Mutating route with no authorisation signal"],
    description: [
      "مسار POST/PUT/PATCH/DELETE لا يظهر في جسمه أي فحص مصادقة أو ملكية أو دور.",
      "A POST/PUT/PATCH/DELETE route shows no authentication, ownership or role check in its handler.",
    ],
    impact: ["قد يسمح لمستخدم بتغيير بيانات لا يملكها — يحتاج تأكيدًا من الفريق.", "A user may be able to modify data they do not own — this needs team confirmation."],
    recommendation: ["أضف فحص مصادقة ثم فحص ملكية/دور قبل أي تعديل، وسجّل سياسة صريحة.", "Add an authentication check followed by an ownership/role check before mutating, with an explicit policy."],
    detection: ["استخراج جسم المعالج والبحث عن دوال/وسائط تصريح", "Handler body extraction followed by a search for auth/policy constructs"],
    references: [CWE(862), OWASP],
  }),
  def({
    id: "API-002",
    engine: "api",
    category: "api",
    severity: "MEDIUM",
    confidence: 0.6,
    languages: ["javascript", "typescript", "php", "python", "ruby"],
    title: ["مسار يستخدم مدخل الطلب بلا تحقق ظاهر", "Route uses request input without visible validation"],
    description: ["قيم الطلب تُستخدم مباشرة في الاستعلام أو الحفظ بلا مخطط تحقق.", "Request values flow straight into a query or write without a validation schema."],
    impact: ["مدخلات غير متوقعة تسبب أخطاء أو كتابة بيانات غير صالحة.", "Unexpected input causes errors or stores invalid data."],
    recommendation: ["تحقق بمخطط (zod/Joi/FormRequest/Serializer) عند حدود النظام.", "Validate with a schema (zod/Joi/FormRequest/Serializer) at the system boundary."],
    detection: ["استخدام req.body/request.data مع غياب مخطط تحقق", "Use of req.body/request.data without a validation schema"],
    references: [CWE(20)],
  }),
  def({
    id: "API-003",
    engine: "api",
    category: "api",
    severity: "MEDIUM",
    confidence: 0.7,
    languages: ["javascript", "typescript", "php", "python", "ruby", "java"],
    title: ["كشف تفاصيل داخلية في رسالة الخطأ", "Internal details exposed in error responses"],
    description: ["استجابة الخطأ تحتوي stack trace أو رسالة النظام الأصلية.", "An error response exposes a stack trace or the raw system message."],
    impact: ["يكشف بنية المشروع والمسارات وإصدارات المكتبات للمهاجم.", "It reveals project structure, paths and library versions to an attacker."],
    recommendation: ["أعِد رسالة عامة مع معرّف تتبع، واحتفظ بالتفاصيل في السجل.", "Return a generic message with a trace id, and keep details in the logs."],
    detection: ["إرجاع error.message/stack في الاستجابة", "Returning error.message/stack in the response"],
    references: [CWE(209)],
  }),
  def({
    id: "API-004",
    engine: "api",
    category: "api",
    severity: "LOW",
    confidence: 0.55,
    languages: "all",
    title: ["مسارات مصادقة بلا إشارة تحديد معدل", "Auth routes with no rate-limit signal"],
    description: ["مسارات الدخول/التسجيل/التحقق لا تُظهر أي تحديد معدل الطلبات.", "Login/registration/verification routes show no request throttling."],
    impact: ["تخمين كلمات المرور أو إغراق الطلبات يصبح أسهل.", "Password guessing or request flooding becomes easier."],
    recommendation: ["أضف Middleware لتحديد المعدل مع تسجيل المحاولات الفاشلة.", "Add rate-limiting middleware and record failed attempts."],
    detection: ["مسارات المصادقة + غياب وسيط التحديد", "Auth routes without throttling middleware"],
    references: [CWE(307)],
  }),
  def({
    id: "API-005",
    engine: "api",
    category: "api",
    severity: "HIGH",
    confidence: 0.7,
    languages: ["javascript", "typescript", "php", "python", "ruby"],
    title: ["إرجاع كائن المستخدم كاملًا (بما فيه كلمة المرور)", "Returning a full user object including credentials"],
    description: ["استجابة تعيد الكائن كاملًا مع حقول مثل password أو token أو secret.", "A response returns the whole object including fields such as password, token or secret."],
    impact: ["تسريب بيانات اعتماد عبر API يمكن استغلاله مباشرة.", "Credential leakage through an API that can be used directly."],
    recommendation: ["استخدم DTO/Resource وحدّد الحقول المسموحة في الاستجابة.", "Use a DTO/Resource and whitelist the fields returned."],
    detection: ["إرجاع كائن + اختيار حقول حساسة أو select *", "Object returned alongside sensitive field selection or select *"],
    references: [CWE(213)],
  }),
  def({
    id: "API-006",
    engine: "api",
    category: "api",
    severity: "LOW",
    confidence: 0.6,
    languages: ["javascript", "typescript", "php", "python", "ruby"],
    title: ["قائمة بلا ترقيم صفحات", "List endpoint without pagination"],
    description: ["مسار يعيد قائمة كاملة بلا limit/offset أو cursor.", "A route returns a full list without limit/offset or a cursor."],
    impact: ["استجابة ضخمة وبطء تدريجي مع نمو البيانات.", "A heavy response that degrades as data grows."],
    recommendation: ["أضف ترقيمًا بحد أقصى واضح واستعلامًا مقيّدًا.", "Add pagination with a sane maximum and a bounded query."],
    detection: ["دوال البحث/الجلب التي تعيد كل السجلات", "Find/all calls that return every record"],
    references: [],
  }),

  /* ---------------------------- database --------------------------- */
  def({
    id: "DBN-001",
    engine: "database",
    category: "database",
    severity: "MEDIUM",
    confidence: 0.7,
    languages: "all",
    title: ["عمود مفتاح أجنبي بلا فهرس", "Foreign key column without an index"],
    description: ["مخطط الجداول يعرّف مفتاحًا أجنبيًا بلا فهرس صريح عليه.", "The schema defines a foreign key with no explicit index on the column."],
    impact: ["استعلامات الربط تصبح بطيئة جدًا مع نمو البيانات.", "Join queries slow down badly as data grows."],
    recommendation: ["أضف فهرسًا على عمود المفتاح الأجنبي في ترحيل جديد.", "Add an index on the foreign key column in a new migration."],
    detection: ["تحليل ملفات الترحيلات/المخطط", "Parsing migration and schema files"],
    references: [],
  }),
  def({
    id: "DBN-002",
    engine: "database",
    category: "database",
    severity: "LOW",
    confidence: 0.6,
    languages: "all",
    title: ["عمود يمثل هوية بلا قيد تفرّد", "Identity-like column without a unique constraint"],
    description: ["عمود مثل email/username/phone بلا فهرس فريد.", "A column such as email/username/phone has no unique constraint."],
    impact: ["إمكانية تسجيل بيانات مكررة وتناقضها لاحقًا.", "Duplicate records can be created and diverge later."],
    recommendation: ["أضف قيد UNIQUE بعد تنظيف البيانات المكررة الحالية.", "Add a UNIQUE constraint after cleaning existing duplicates."],
    detection: ["أسماء أعمدة معروفة + غياب unique", "Known column names without a unique constraint"],
    references: [],
  }),
  def({
    id: "DBN-003",
    engine: "database",
    category: "database",
    severity: "MEDIUM",
    confidence: 0.65,
    languages: ["javascript", "typescript", "php", "python", "ruby", "java"],
    title: ["نمط N+1 محتمل", "Possible N+1 query pattern"],
    description: ["استعلام قاعدة بيانات داخل حلقة أو map على مجموعة نتائج.", "A database call sits inside a loop or a map over results."],
    impact: ["عدد الاستعلامات ينمو مع عدد الصفوف، ويتدهور الأداء بسرعة.", "Queries grow with row count and performance degrades quickly."],
    recommendation: ["استخدم eager loading أو استعلامًا واحدًا بدمج، أو أجّل التنفيذ على دفعات.", "Use eager loading or a single join, or batch the work."],
    detection: ["نداء قاعدة بيانات داخل كتلة تكرار", "Database call detected inside an iteration block"],
    references: [],
  }),
  def({
    id: "DBN-004",
    engine: "database",
    category: "database",
    severity: "LOW",
    confidence: 0.7,
    languages: ["javascript", "typescript", "php", "python", "ruby", "java"],
    title: ["استعلام يجلب كل الأعمدة", "Query selecting every column"],
    description: ["استعلام يستخدم SELECT * بدل تحديد الأعمدة المطلوبة.", "A query uses SELECT * instead of naming the needed columns."],
    impact: ["بيانات حساسة قد تُقرأ بلا داعٍ، وأداء أقل مع الجداول الكبيرة.", "Sensitive data may be read unnecessarily, with worse performance on wide tables."],
    recommendation: ["حدّد الأعمدة المطلوبة صريحًا.", "Name the required columns explicitly."],
    detection: ["أنماط SELECT * في الاستعلامات", "SELECT * patterns in queries"],
    references: [],
  }),
  def({
    id: "DBN-005",
    engine: "database",
    category: "database",
    severity: "LOW",
    confidence: 0.8,
    languages: "all",
    title: ["ترحيل يُسقط جدولًا أو عمودًا", "Migration drops a table or column"],
    description: ["ترحيل جديد يحذف جدولًا أو عمودًا — لا رجعة بعد التنفيذ.", "A new migration drops a table or column — it cannot be undone after running."],
    impact: ["فقدان بيانات غير قابل للاستعادة إن لم يكن منسوخًا مسبقًا.", "Unrecoverable data loss if no backup was taken first."],
    recommendation: ["انقل البيانات أولًا، ونفّذ الإسقاط في ترحيل لاحق بعد التأكد ونسخة احتياطية.", "Migrate the data first, then drop in a later migration once verified and backed up."],
    detection: ["عبارات drop/delete في ملفات الترحيلات", "drop/delete statements in migration files"],
    references: [],
  }),

  /* ------------------------------- ops ----------------------------- */
  def({
    id: "OPS-001",
    engine: "ops",
    category: "ops",
    severity: "MEDIUM",
    confidence: 0.8,
    languages: "all",
    title: ["الحاوية تعمل بصلاحيات root", "Container runs as root"],
    description: ["ملف Dockerfile لا يحدد مستخدمًا غير root (USER).", "The Dockerfile never switches to a non-root USER."],
    impact: ["أي اختراق داخل الحاوية يقترب من صلاحيات المضيف.", "Any compromise inside the container gets closer to host privileges."],
    recommendation: ["أنشئ مستخدمًا محدودًا وبدّل إليه قبل CMD.", "Create an unprivileged user and switch to it before CMD."],
    detection: ["تحليل تعليمات Dockerfile", "Dockerfile instruction analysis"],
    references: ["https://docs.docker.com/develop/develop-images/dockerfile_best-practices/"],
  }),
  def({
    id: "OPS-002",
    engine: "ops",
    category: "ops",
    severity: "LOW",
    confidence: 0.85,
    languages: "all",
    title: ["صورة أساس غير مثبَّتة الإصدار", "Unpinned base image"],
    description: ["‏FROM يستخدم latest أو بلا إصدار محدد.", "FROM uses latest or no fixed version."],
    impact: ["بناء متغيّر بلا تحكّم، وقد يتغير فجأة بين نشرين.", "Uncontrolled builds that can change between deployments."],
    recommendation: ["ثبّت وسوم إصدار محددة أو hash للصورة.", "Pin explicit version tags or an image digest."],
    detection: ["وسوم صور Dockerfile", "Dockerfile image tags"],
    references: [],
  }),
  def({
    id: "OPS-003",
    engine: "ops",
    category: "ops",
    severity: "HIGH",
    confidence: 0.85,
    languages: "all",
    title: ["تنفيذ سكربت بعيد أثناء البناء", "Remote script executed during build"],
    description: ["‏RUN ينفّذ curl|bash أو تحميلًا مباشرًا من الإنترنت.", "A RUN step pipes curl into bash or downloads and runs remote code."],
    impact: ["بناء غير قابل للتتبع قد يحمل كودًا خبيثًا.", "An untraceable build that may pull in malicious code."],
    recommendation: ["نزّل بإصدار وhash محددين وتحقق من التوقيع.", "Download with a pinned version and verify a checksum or signature."],
    detection: ["أنماط تنزيل وتنفيذ في Dockerfile", "Download-and-execute patterns in Dockerfiles"],
    references: [],
  }),
  def({
    id: "OPS-004",
    engine: "ops",
    category: "ops",
    severity: "HIGH",
    confidence: 0.85,
    languages: "all",
    title: ["أسرار مكتوبة في ملفات CI", "Secrets written into CI workflow files"],
    description: ["سير عمل CI يحمل قيمًا سرية كنص صريح بدل متغيرات محمية.", "A CI workflow contains literal secret values instead of protected variables."],
    impact: ["الأسرار متاحة لكل من يقرأ سير العمل أو سجلاته.", "Secrets are readable by anyone who can view the workflow or its logs."],
    recommendation: ["استخدم أسرار المنصة (Secrets) عبر متغيرات، وأبطِل القيم المكشوفة.", "Use the platform's secret store via variables, and revoke the exposed values."],
    detection: ["مفاتيح YAML معروفة في ملفات CI", "Known YAML keys inside CI files"],
    references: [CWE(798)],
  }),
  def({
    id: "OPS-005",
    engine: "ops",
    category: "ops",
    severity: "HIGH",
    confidence: 0.8,
    languages: "all",
    title: ["حاوية بصلاحيات موسّعة", "Privileged container configuration"],
    description: ["إعداد privileged أو host network يمنح الحاوية صلاحيات المضيف.", "A privileged or host-network setting grants host-level access."],
    impact: ["اختراق الحاوية يعني اختراق المضيف والشبكة.", "A container compromise becomes a host and network compromise."],
    recommendation: ["أزل التعليمات، وحدّد القدرات والشبكات بأقل صلاحية.", "Remove it and grant only the capabilities and networks actually needed."],
    detection: ["خيارات privileged/host في Docker وdocker-compose", "privileged/host options in Docker and docker-compose"],
    references: [],
  }),
  def({
    id: "OPS-006",
    engine: "ops",
    category: "ops",
    severity: "INFO",
    confidence: 0.9,
    languages: "all",
    title: ["لا يوجد .dockerignore", "No .dockerignore"],
    description: ["بناء الحاوية ينسخ كل شيء بما فيه node_modules وملفات الأسرار.", "The build context includes everything, including node_modules and secret files."],
    impact: ["صور أكبر وتسريب محتمل لملفات حساسة داخل الطبقات.", "Larger images and possible leakage of sensitive files into layers."],
    recommendation: ["أضف .dockerignore يستبعد .git وnode_modules و*.env.", "Add a .dockerignore excluding .git, node_modules and *.env."],
    detection: ["وجود Dockerfile مع غياب .dockerignore", "Dockerfile present without .dockerignore"],
    references: [],
  }),
  def({
    id: "OPS-007",
    engine: "ops",
    category: "ops",
    severity: "INFO",
    confidence: 0.95,
    languages: "all",
    title: ["لا يوجد .gitignore", "No .gitignore"],
    description: ["المستودع بلا ملف .gitignore.", "The repository has no .gitignore file."],
    impact: ["رفع ملفات أسرار أو مخرجات بناء بالخطأ وارد جدًا.", "Secret files or build output are easily committed by mistake."],
    recommendation: ["أضف .gitignore يستبعد الأسرار والمخرجات والتغطية.", "Add a .gitignore covering secrets, build output and coverage."],
    detection: ["غياب ملف .gitignore", "Absence of the .gitignore file"],
    references: [],
  }),

  /* ------------------------------ tests ---------------------------- */
  def({
    id: "TST-001",
    engine: "tests",
    category: "tests",
    severity: "MEDIUM",
    confidence: 0.9,
    languages: "all",
    title: ["لا اختبارات في المشروع", "No tests in the project"],
    description: ["لم يُعثر على أي ملف اختبار ولم يُكتشف إطار اختبار.", "No test file was found and no test framework was detected."],
    impact: ["أي تعديل ينشر بلا شبكة أمان، والأخطاء تُكتشف في الإنتاج.", "Every change ships without a safety net and bugs surface in production."],
    recommendation: ["ابدأ باختبارات للوحدات الحرجة (مصادقة، دفع، وصول للبيانات).", "Start with tests for the critical paths: auth, payments and data access."],
    detection: ["أنماط أسماء ملفات الاختبار + إعدادات الحزم", "Test file name patterns plus package configuration"],
    references: [],
  }),
  def({
    id: "TST-002",
    engine: "tests",
    category: "tests",
    severity: "HIGH",
    confidence: 0.95,
    languages: "all",
    title: ["اختبارات فاشلة في النتائج المرفوعة", "Failing tests in the committed results"],
    description: ["ملف نتائج مرفوع مع المشروع يحتوي حالات فاشلة.", "A test result file committed with the project contains failing cases."],
    impact: ["المشروع ينشر بمعرفة مسبقة باختبارات فاشلة.", "The project ships with known failing tests."],
    recommendation: ["أصلح أو عطّل الاختبارات الفاشلة بشكل صريح مع تتبّع السبب.", "Fix the failing tests or explicitly skip them with a tracked reason."],
    detection: ["تحليل JUnit XML المرفوع", "Parsing committed JUnit XML"],
    references: [],
  }),
  def({
    id: "TST-003",
    engine: "tests",
    category: "tests",
    severity: "MEDIUM",
    confidence: 0.9,
    languages: "all",
    title: ["تغطية اختبارات منخفضة", "Low test coverage"],
    description: ["نسبة التغطية المعلنة في تقرير التغطية أقل من 50%.", "The coverage reported by the committed coverage report is below 50%."],
    impact: ["معظم الكود غير مُختبَر، والانحدارات تمر بصمت.", "Most code is untested and regressions pass silently."],
    recommendation: ["غطِّ المسارات الحرجة أولًا، ثم ارفع الحد تدريجيًا في CI.", "Cover critical paths first, then raise the threshold gradually in CI."],
    detection: ["قراءة lcov/coverage-summary.json", "Reading lcov/coverage-summary.json"],
    references: [],
  }),
  def({
    id: "TST-004",
    engine: "tests",
    category: "tests",
    severity: "LOW",
    confidence: 0.7,
    languages: "all",
    title: ["اختبارات موجودة بلا أمر تشغيل موثّق", "Tests exist without a documented run command"],
    description: ["ملفات اختبار موجودة لكن لا يوجد سكربت تشغيل واضح في ملفات الحزم.", "Test files exist but no clear run script in the package manifests."],
    impact: ["من الصعب على الفريق تشغيل نفس الاختبارات محليًا أو في CI.", "The team cannot easily run the same tests locally or in CI."],
    recommendation: ["أضف سكربت test موثّقًا واذكره في README.", "Add a documented test script and mention it in the README."],
    detection: ["وجود ملفات اختبار + سكربتات الحزم", "Presence of test files compared with package scripts"],
    references: [],
  }),
  def({
    id: "TST-005",
    engine: "tests",
    category: "tests",
    severity: "LOW",
    confidence: 0.8,
    languages: ["javascript", "typescript", "python", "php", "java", "dart"],
    title: ["اختبارات معطّلة (skip/only)", "Skipped or focused tests"],
    description: ["وجود .skip/.only أو @Ignore في ملفات الاختبار.", ".skip/.only or @Ignore appears in test files."],
    impact: ["اختبار مهم لا يعمل فعلًا، أو اختبار واحد فقط يُنفَّذ ويخفي غيره.", "An important test never runs, or only one test runs and hides the rest."],
    recommendation: ["أزل skip/only وأصلح الاختبار، أو وثّق سبب تعطيله.", "Remove skip/only and fix the test, or document why it is disabled."],
    detection: ["وسوم تعطيل الاختبارات", "Test-disabling markers"],
    references: [],
  }),
];

export const RULES_BY_ID: Record<string, RuleDef> = Object.fromEntries(
  RULE_CATALOG.map((rule) => [rule.id, rule]),
);

export function getRule(id: string): RuleDef | undefined {
  return RULES_BY_ID[id];
}

export function ruleStats() {
  return {
    total: RULE_CATALOG.length,
    version: RULE_CATALOG_VERSION,
    byCategory: RULE_CATALOG.reduce<Record<string, number>>((acc, rule) => {
      acc[rule.category] = (acc[rule.category] ?? 0) + 1;
      return acc;
    }, {}),
  };
}

export const SUPPORTED_LANGUAGES = Array.from(
  new Set(RULE_CATALOG.flatMap((rule) => (rule.languages === "all" ? [] : rule.languages))),
).sort();
